import test from 'node:test';
import assert from 'node:assert/strict';
import {parsePublicationFeed,runEconomicsNow} from '../src/admin-runs.js';

const rss=`<?xml version="1.0"?><rss><channel><item><title>Central bank weighs rate cut</title><link>https://example.com/a</link><description>Officials are balancing inflation and employment.</description><pubDate>Tue, 05 Aug 2026 10:00:00 GMT</pubDate></item></channel></rss>`;

test('parses RSS publication metadata',()=>{const rows=parsePublicationFeed(rss,'rss',10);assert.equal(rows.length,1);assert.equal(rows[0].title,'Central bank weighs rate cut');assert.equal(rows[0].url,'https://example.com/a')});

test('saves headline-first problems when no AI provider exists',async()=>{let captured=[];const fetchImpl=async()=>new Response(rss,{status:200});const result=await runEconomicsNow({fetchImpl,settings:{source_url:'https://feed.example/rss',source_type:'rss',source_name:'Example',max_items:8,ai_items_per_run:6},providers:[],instruction:'Analyze.',onHeadlines:async rows=>{captured=rows}});assert.equal(result.ok,true);assert.equal(result.inserted,1);assert.equal(result.enriched,0);assert.equal(result.headlineOnly,1);assert.equal(captured.length,1);assert.equal(captured[0].title,'Central bank weighs rate cut');assert.equal(captured[0].enrichment_status,'headline-only')});

test('accepts code-fenced JSON from an OpenRouter-compatible model',async()=>{const urls=[];const fetchImpl=async url=>{urls.push(String(url));if(String(url).includes('feed.example'))return new Response(rss,{status:200});return new Response(JSON.stringify({model:'nvidia/nemotron-test',choices:[{message:{content:'```json\n{"stories":[{"index":0,"problem":"Policymakers must balance inflation risk against labor-market weakness.","questions":["How persistent is inflation?"],"topics":["monetary policy"]}]}\n```'}}]}),{status:200,headers:{'Content-Type':'application/json'}})};const result=await runEconomicsNow({fetchImpl,settings:{source_url:'https://feed.example/rss',source_type:'rss',source_name:'Example',max_items:8,ai_items_per_run:6},providers:[{name:'primary',endpoint:'https://openrouter.ai/api/v1/chat/completions',model:'nvidia/nemotron-test',key:'secret'}],instruction:'Analyze.'});assert.equal(result.enriched,1);assert.equal(result.problems[0].ai_model,'nvidia/nemotron-test');assert.equal(urls[1],'https://openrouter.ai/api/v1/chat/completions')});
