import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8');

test('current onboarding module parses and loads after the command center',()=>{const js=read('../public/game-onboarding-v2.js'),html=read('../public/game.html');assert.doesNotThrow(()=>new Function(js.replace(/^import[^;]+;/,'')));assert.match(html,/game-onboarding-v2\.css/);assert.match(html,/game-onboarding-v2\.js/);assert.ok(html.indexOf('game-onboarding-v2.js')>html.indexOf('game-command-center.js'));assert.doesNotMatch(js,/new MutationObserver/)});

test('walkthrough uses its own spotlight and curved white arrow instead of elevating dashboard targets above the overlay',()=>{const js=read('../public/game-onboarding-v2.js'),css=read('../public/game-onboarding-v2.css');assert.match(js,/onboarding-spotlight/);assert.match(js,/<svg class="onboarding-arrow"/);assert.match(js,/coach-arrow-head/);assert.match(js,/ C \$\{bendX\}/);assert.match(css,/stroke:#fff/);assert.match(css,/marker-end:url\(#coach-arrow-head\)/);assert.match(css,/onboarding-scrim/);assert.match(css,/z-index:7000/);assert.doesNotMatch(css,/game-tour-open #game-objective-banner/)});

test('mobile tour scrolls each target into view and waits for scrolling to settle before drawing the card',()=>{const js=read('../public/game-onboarding-v2.js');assert.match(js,/targetScrollTop/);assert.match(js,/window\.scrollTo/);assert.match(js,/settleTarget/);assert.match(js,/requestAnimationFrame\(tick\)/);assert.match(js,/window\.innerHeight\*\.3/)});

test('walkthrough has explicit exit controls and first intro can also be dismissed',()=>{const js=read('../public/game-onboarding-v2.js'),css=read('../public/game-onboarding-v2.css');assert.match(js,/data-tour-close/);assert.match(js,/data-tour-dismiss/);assert.match(js,/Exit tour/);assert.match(js,/dataIntroClose/);assert.match(js,/dismissIntro/);assert.match(css,/onboarding-close/);assert.match(css,/intro-close/)});

test('tour explicitly teaches order clearance solvency time decisions working capital map and departments',()=>{const js=read('../public/game-onboarding-v2.js');for(const target of['#game-objective-banner','.clock','.orders-panel','.working-capital-cash','#map-panel','#open-team'])assert.match(js,new RegExp(target.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(js,/Fill and clear customer orders/);assert.match(js,/stay solvent/);assert.match(js,/Cash, A\/R and A\/P/);assert.match(js,/15 real minutes equals one game hour/);assert.match(js,/origin, current location, destination/)});

test('tour seen state is versioned inside the same offline and account-synced career',()=>{const js=read('../public/game-onboarding-v2.js'),progress=read('../public/progress-v2.js');assert.match(js,/const TOUR_VERSION=3/);assert.match(js,/dashboardTourVersion:TOUR_VERSION/);assert.match(js,/state\.onboarding=/);assert.match(js,/localStorage\.setItem\(GAME_KEY/);assert.match(js,/atlas-game-changed/);assert.match(progress,/user_metadata\?\.atlas_problem_spaces\?\.logistics_game\?\.progress/)});

test('new tutorial owns the first command click so the older command-center coachmark cannot double-open',()=>{const js=read('../public/game-onboarding-v2.js');assert.match(js,/document\.addEventListener\('click',interceptTakeCommand,true\)/);assert.match(js,/event\.stopImmediatePropagation\(\)/);assert.match(js,/state\.onboardingComplete=true/);assert.match(js,/state\.tutorialDone=true/);assert.match(js,/writeState\(state,\{reload:true\}\)/);assert.match(js,/setTimeout\(\(\)=>start\(false\),350\)/);assert.match(js,/data-restart-tour/)});

test('mobile decision navigation makes waiting counters actionable and exception sheets closable',()=>{const js=read('../public/game-mobile-navigation.js');assert.doesNotThrow(()=>new Function(js));assert.match(js,/#decision-count/);assert.match(js,/#alert-count/);assert.match(js,/openNextDecision/);assert.match(js,/\.map-alert \[data-alert\]/);assert.match(js,/decision-close-mobile/);assert.match(js,/Close exception decision without taking action/);assert.match(js,/top:calc\(66px \+ env\(safe-area-inset-top\)\)/);assert.match(js,/dispatch-decision-portal/);assert.match(js,/portal-close/)});

test('startup replay controller targets ten seconds and keeps finance replay duration synchronized',()=>{const controller=read('../public/game-replay-controller.js'),html=read('../public/game.html');assert.doesNotThrow(()=>new Function(controller));assert.match(controller,/TARGET_MS=10000/);assert.match(controller,/callback\?\.name!==['"]replayStep['"]/);assert.match(controller,/event\.detail\.duration=TARGET_MS/);assert.match(controller,/atlas-global-replay-start/);assert.ok(html.indexOf('game-replay-controller.js')<html.indexOf('game-global-simulation-v2.js'));assert.ok(html.indexOf('game-replay-controller.js')<html.indexOf('game-finance.js'))});
