import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8');

test('stable browser game modules parse as JavaScript',()=>{for(const path of['../public/game-map-bridge.js','../public/game-management-v3.js','../public/game-global-simulation.js'])assert.doesNotThrow(()=>new Function(read(path)),`${path} must parse`)});

test('game loads the realistic global 3PL management runtime',()=>{const html=read('../public/game.html');assert.match(html,/game-management\.css/);assert.match(html,/game-management-v3\.css/);assert.match(html,/game-global-simulation\.css/);assert.match(html,/game-map-bridge\.js/);assert.match(html,/game-management-v3\.js/);assert.match(html,/game-global-simulation\.js/);assert.doesNotMatch(html,/src="\/game-management-v2\.js"/);assert.doesNotMatch(html,/src="\/game-management\.js"/);assert.match(html,/General Manager & Lead Dispatcher/)});

test('management runtime keeps the freeze guardrail',()=>{const js=read('../public/game-management-v3.js'),global=read('../public/game-global-simulation.js');for(const source of[js,global]){assert.doesNotMatch(source,/new MutationObserver/);assert.doesNotMatch(source,/document\.documentElement[\s\S]*subtree:true/)}assert.match(js,/scheduleRefresh/);assert.match(global,/setInterval\(updatePositions,850\)/)});

test('department hiring is an agency requisition with fee lead time and no instant headcount increment',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/const AGENCY_RATE=\.20/);assert.match(js,/staffingPipeline/);assert.match(js,/Request 1 hire/);assert.match(js,/Approve requisition/);assert.match(js,/Agency placement fee/);assert.match(js,/readyAt:gameHour\(\)\+s\.leadHours/);assert.match(js,/management\.departments\[req\.department\]\.headcount\+=1/);assert.doesNotMatch(js,/data-request-hire[\s\S]{0,1200}headcount\+=1/)});

test('people budget includes annual payroll monthly payroll and recurring labor burn',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/annualPayroll\(\)/);assert.match(js,/Monthly people payroll/);assert.match(js,/Annual people budget/);assert.match(js,/annualPayroll\(\)\/8760\*elapsed/);assert.match(js,/Operating payroll and lease costs/);for(const salary of['82000','76000','70000','96000'])assert.match(js,new RegExp(salary))});

test('department cards show active people pending hires and salary at a glance',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/active people/);assert.match(js,/agency pipeline/);assert.match(js,/annual payroll/);assert.match(js,/next hire salary/);assert.match(js,/20% first-year salary placement fee/)});

test('capacity distinguishes owned leased contracted and partner accessible inventory',()=>{const js=read('../public/game-management-v3.js');for(const text of['Owned','Leased','Contracted','Partner accessible','Immediately controlled'])assert.match(js,new RegExp(text));assert.match(js,/Buy class-8 tractor/);assert.match(js,/Lease class-8 tractor/);assert.match(js,/Lease 53 ft dry van/);assert.match(js,/Contract 10 FEU ocean block/);assert.match(js,/Contract 16-pallet air block/);assert.match(js,/access:\{Ocean:18\}/);assert.match(js,/access:\{Ocean:12,Air:34\}/)});

test('capacity procurement has lead time recurring costs and a pending pipeline',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/capacityPipeline/);assert.match(js,/Review commitment/);assert.match(js,/Monthly recurring asset cost/);assert.match(js,/Controlled after arrival/);assert.match(js,/readyAt:gameHour\(\)\+item\.leadHours/);assert.match(js,/management\.fleet\.push\(\{\.\.\.req\.asset/)});

test('financial and operating actions use a review confirmation surface',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/REVIEW COMMITMENT/);assert.match(js,/Current cash/);assert.match(js,/Cash after confirmation/);assert.match(js,/reviewMaintenance/);assert.match(js,/reviewCarrierContract/);assert.match(js,/reviewDriverHire/);assert.match(js,/reviewLoadOffer/);assert.match(js,/reviewLaneBooking/);assert.match(js,/reviewDelegation/);assert.match(js,/reviewPolicy/)});

test('main game map remains global with live moving multimodal traffic',()=>{const bridge=read('../public/game-map-bridge.js'),js=read('../public/game-management-v3.js'),global=read('../public/game-global-simulation.js'),html=read('../public/game.html');assert.match(bridge,/__atlasMainGameMap/);assert.match(js,/fitGlobal/);assert.match(js,/Focus active chapter/);assert.match(global,/mode:'truck'/);assert.match(global,/mode:'ocean'/);assert.match(global,/mode:'air'/);assert.match(global,/🚚/);assert.match(global,/🚢/);assert.match(global,/✈️/);assert.match(html,/live global supply chain/i)});

test('routine departments and global trade workload stay interactive',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/#open-team/);assert.match(js,/\.automation-state/);assert.match(js,/Dispatch & Capacity/);assert.match(js,/Production Control/);assert.match(js,/Customer Operations/);assert.match(js,/Global Trade Desk/);assert.match(js,/atlasRoutineGlobalMoveCount/);assert.match(js,/delegation:\{dispatch:/)});

test('fleet carrier and HR systems remain playable',()=>{const js=read('../public/game-management-v3.js');assert.match(js,/Owned truck/);assert.match(js,/Contracted vessel slot/);assert.match(js,/reputation/);assert.match(js,/relationship/);assert.match(js,/Call carrier/);assert.match(js,/Review capacity contract/);assert.match(js,/Review priority load offer/);assert.match(js,/Staffing-agency candidate slate/)});

test('management state remains inside the same cloud-synced game object',()=>{const js=read('../public/game-management-v3.js'),progress=read('../public/progress-v2.js');assert.match(js,/management:clone\(management\)/);assert.match(js,/window\.__atlasGameState/);assert.match(js,/atlas-game-loaded/);assert.match(js,/atlas-game-changed/);assert.match(progress,/user_metadata\?\.atlas_problem_spaces\?\.logistics_game\?\.progress/);assert.match(progress,/window\.__atlasGameState/)});

test('game documentation describes realistic staffing and capacity commitments',()=>{const docs=read('../docs/logistics-game/README.md'),manual=read('../public/game-docs.html');for(const text of[docs,manual]){assert.match(text,/General Manager/);assert.match(text,/staffing agency/i);assert.match(text,/20%/);assert.match(text,/owned/i);assert.match(text,/leased/i);assert.match(text,/partner-accessible|partner accessible/i);assert.match(text,/confirmation|review/i)}});