import test from 'node:test';
import assert from 'node:assert/strict';
import {fuelPrices} from '../src/game-fuel.js';

const response=(body,{status=200,headers={}}={})=>new Response(body,{status,headers});

test('fuel service keeps explicit official and scenario fallbacks without external credentials',async()=>{const fetchImpl=async url=>{const value=String(url);if(value.includes('gov.uk/government/statistics/weekly-road-fuel-prices'))return response('<a href="https://assets.publishing.service.gov.uk/media/test/weekly_road_fuel_prices_2026.csv">CSV</a>');if(value.includes('weekly_road_fuel_prices_2026.csv'))return response('Date,ULSP,ULSD\n20/07/2026,144.00,167.08\n27/07/2026,149.00,173.97\n03/08/2026,154.00,179.19\n');throw new Error(`unexpected ${value}`)};const data=await fuelPrices({fetchImpl,env:{}});assert.equal(data.prices['United States'].quality,'official-fallback');assert.equal(data.prices['United Kingdom'].quality,'official-live');assert.equal(data.prices['United Kingdom'].localValue,179.19);assert.equal(data.prices['United Kingdom'].localWeekAgo,173.97);assert.equal(data.prices['China'].quality,'scenario-baseline');assert.equal(data.meta.eiaApiConfigured,false)});

test('configured EIA key replaces US fallback with latest two official weekly diesel values',async()=>{const fetchImpl=async url=>{const value=String(url);if(value.includes('api.eia.gov'))return response(JSON.stringify({response:{data:[{period:'2026-08-03',value:'5.348'},{period:'2026-07-27',value:'5.313'}]}}),{headers:{'content-type':'application/json'}});if(value.includes('gov.uk/government/statistics/weekly-road-fuel-prices'))return response('<a href="https://assets.publishing.service.gov.uk/media/test/weekly_road_fuel_prices_2026.csv">CSV</a>');if(value.includes('weekly_road_fuel_prices_2026.csv'))return response('Date,ULSP,ULSD\n27/07/2026,149.00,173.97\n03/08/2026,154.00,179.19\n');throw new Error(`unexpected ${value}`)};const data=await fuelPrices({fetchImpl,env:{EIA_API_KEY:'test-key'}}),us=data.prices['United States'];assert.equal(us.quality,'official-live');assert.equal(us.localValue,5.348);assert.equal(us.localWeekAgo,5.313);assert.equal(us.sourceDate,'2026-08-03');assert.ok(us.weeklyDeltaPct>0)});

test('fuel service exposes all requested global markets even when live adapters fail',async()=>{const fetchImpl=async()=>{throw new Error('offline')};const data=await fuelPrices({fetchImpl,env:{}});for(const country of['United States','United Kingdom','Netherlands','China','South Korea','Japan','Australia','United Arab Emirates','India','Kenya','Indonesia','Colombia'])assert.ok(data.prices[country],country);assert.equal(data.prices['United Kingdom'].quality,'official-fallback');assert.match(data.meta.ukError,/offline/)});
