import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8');

test('stable browser game modules parse as JavaScript',()=>{for(const path of['../public/game-map-bridge.js','../public/game-management-v2.js','../public/game-global-simulation.js'])assert.doesNotThrow(()=>new Function(read(path)),`${path} must parse`)});

test('game loads only the stable global 3PL management runtime',()=>{const html=read('../public/game.html');assert.match(html,/game-management\.css/);assert.match(html,/game-global-simulation\.css/);assert.match(html,/game-map-bridge\.js/);assert.match(html,/game-management-v2\.js/);assert.match(html,/game-global-simulation\.js/);assert.doesNotMatch(html,/src="\/game-management\.js"/);assert.match(html,/General Manager & Lead Dispatcher/);assert.match(html,/Global 3PL Control Tower/i)});

test('stable management runtime never observes the whole document',()=>{const js=read('../public/game-management-v2.js'),global=read('../public/game-global-simulation.js');for(const source of[js,global]){assert.doesNotMatch(source,/new MutationObserver/);assert.doesNotMatch(source,/document\.documentElement[\s\S]*subtree:true/)}assert.match(js,/scheduleRefresh/);assert.match(js,/setTimeout\(\(\)=>\{renderDeck/);assert.match(global,/setInterval\(updatePositions,850\)/)});

test('main game map is bridged and opens on the global network',()=>{const bridge=read('../public/game-map-bridge.js'),js=read('../public/game-management-v2.js'),html=read('../public/game.html');assert.match(bridge,/__atlasMainGameMap/);assert.match(js,/fitGlobal/);assert.match(js,/fitBounds\(globalBounds/);assert.match(js,/setMinZoom\(2\)/);assert.match(js,/renderMainMapOverlay/);assert.match(js,/Focus active chapter/);assert.match(html,/Fit global network/)});

test('global map contains live factories ports distribution and moving multimodal vehicles',()=>{const js=read('../public/game-global-simulation.js'),html=read('../public/game.html');for(const term of['Shenzhen Electronics Campus','Busan Mobility Components Plant','Mumbai Healthcare Packaging Plant','Nairobi Coffee Processing Cooperative','Jakarta Furniture Manufacturing Cluster','Shanghai Medical Device Factory','Port of Rotterdam','Port of Mombasa','Port Botany','Inland Empire Distribution Campus'])assert.match(js,new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(js,/mode:'truck'/);assert.match(js,/mode:'ocean'/);assert.match(js,/mode:'air'/);assert.match(js,/🚚/);assert.match(js,/🚢/);assert.match(js,/✈️/);assert.match(js,/setLatLng/);assert.match(js,/openShipment/);assert.match(js,/Global Trade Desk/);assert.match(html,/live global supply chain/i)});

test('international linehaul uses curated geographic corridors and handles the dateline',()=>{const js=read('../public/game-global-simulation.js');assert.match(js,/sea\('busan-port','rotterdam-port',[\s\S]*29\.5,32\.5/);assert.match(js,/sea\('mombasa-port','felix-port',[\s\S]*29\.5,32\.5/);assert.match(js,/sea\('yantian-port','la-port',[\s\S]*36,178/);assert.match(js,/greatCircle/);assert.match(js,/splitDateline/);assert.match(js,/if\(dLng>180\)dLng-=360/);assert.match(js,/if\(dLng<-180\)dLng\+=360/)});

test('global visual traffic respects the game pause control',()=>{const js=read('../public/game-global-simulation.js');assert.match(js,/readGame\(\)\.paused/);assert.match(js,/visualClock\+=delta/);assert.match(js,/atlasRoutineGlobalMoveCount=ROUTINE\.length/)});

test('routine departments open an interactive management console',()=>{const js=read('../public/game-management-v2.js');assert.match(js,/#open-team/);assert.match(js,/\.automation-state/);assert.match(js,/openControl\('departments'\)/);assert.match(js,/Dispatch & Capacity/);assert.match(js,/Production Control/);assert.match(js,/Customer Operations/);assert.match(js,/Global Trade Desk/);assert.match(js,/delegation:\{dispatch:/)});

test('global network covers requested markets and lanes',()=>{const js=read('../public/game-management-v2.js'),live=read('../public/game-global-simulation.js'),combined=js+live;for(const place of['China','South Korea','Netherlands','United Kingdom','Australia','United Arab Emirates','India','Kenya','Japan','Indonesia','Colombia','Cartagena'])assert.match(combined,new RegExp(place.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(combined,/Shanghai/);assert.match(combined,/Rotterdam/);assert.match(combined,/Jebel Ali/);assert.match(combined,/Mombasa/);assert.match(combined,/Tanjung Priok/);assert.match(combined,/Sydney/)});

test('fleet carrier and HR systems remain playable',()=>{const js=read('../public/game-management-v2.js');assert.match(js,/Owned truck/);assert.match(js,/Contracted vessel slot/);assert.match(js,/Contracted air block/);assert.match(js,/Contracted truck/);assert.match(js,/reputation/);assert.match(js,/relationship/);assert.match(js,/Call carrier/);assert.match(js,/Contract capacity/);assert.match(js,/Offer priority load/);assert.match(js,/HR recruiting pipeline/);assert.match(js,/Recruit/)});

test('management state joins the same cloud-synced game object',()=>{const js=read('../public/game-management-v2.js'),progress=read('../public/progress-v2.js');assert.match(js,/management:clone\(management\)/);assert.match(js,/window\.__atlasGameState/);assert.match(js,/atlas-game-loaded/);assert.match(js,/atlas-game-changed/);assert.match(progress,/user_metadata\?\.atlas_problem_spaces\?\.logistics_game\?\.progress/);assert.match(progress,/window\.__atlasGameState/)});

test('game jargon has clickable explainers including challenge lane',()=>{const js=read('../public/game-management-v2.js');assert.match(js,/'challenge lane'/);assert.match(js,/game-info-button/);assert.match(js,/showInfo/);assert.match(js,/Open game glossary/);assert.match(js,/commercial action/i)});

test('game documentation describes the manager dispatcher model',()=>{const docs=read('../docs/logistics-game/README.md'),manual=read('../public/game-docs.html');for(const text of[docs,manual]){assert.match(text,/General Manager/);assert.match(text,/Lead Dispatcher/);assert.match(text,/carrier relationship/i);assert.match(text,/People.*HR|People & HR/s);assert.match(text,/global/i);assert.match(text,/Challenge lane/i)}});
