import test from 'node:test';
import assert from 'node:assert/strict';
import{metadataWorkspaceRecords,normalizeLegacyLegalRecord,newestRecord,upsertWorkspaceRecord,isDiscoverable,workspaceMetadataKey}from'../src/workspace-records.js';

test('legacy legal notes preserve embedded publications',()=>{const row=normalizeLegacyLegalRecord({id:'7',user_id:'u',case_slug:'case-a',title:'Old',body:'ATLAS_WORKSPACE_V1\n'+JSON.stringify({title:'Published view',body:'<p>x</p>',is_shared:true,is_published:true,resource_title:'Case A'}),updated_at:'2026-08-05T10:00:00Z'});assert.equal(row.resource_type,'legal_case');assert.equal(row.resource_id,'case-a');assert.equal(row.title,'Published view');assert.ok(row.share_token.startsWith('legacy-'));assert.equal(isDiscoverable(row),true)});
test('newest record wins across storage adapters',()=>{const value=newestRecord([{id:'a',updated_at:'2026-08-01',title:'old'},{id:'b',updated_at:'2026-08-05',title:'new'}]);assert.equal(value.title,'new')});
test('upsert replaces a shared token without duplicating it',()=>{const rows=upsertWorkspaceRecord([{id:'a',share_token:'same',updated_at:'2026-08-01'}],{id:'b',share_token:'same',updated_at:'2026-08-05',title:'new'});assert.equal(rows.length,1);assert.equal(rows[0].title,'new')});
test('publishing a draft keeps one workspace when its first share token is assigned',()=>{const draft={id:'a',user_id:'u',resource_type:'baseball_player',resource_id:'669461',share_token:null,is_published:false,updated_at:'2026-08-01'},published={...draft,share_token:'new-token',is_shared:true,is_published:true,updated_at:'2026-08-05'};const rows=upsertWorkspaceRecord([draft],published);assert.equal(rows.length,1);assert.equal(rows[0].id,'a');assert.equal(rows[0].share_token,'new-token');assert.equal(rows[0].is_published,true)});
test('segmented records join legacy metadata and preserve deletion tombstones',()=>{const key=workspaceMetadataKey('baseball_player','695491'),rows=metadataWorkspaceRecords({atlas_problem_spaces:{publishing_workspace:{notes:[{id:'old',resource_type:'baseball_player',resource_id:'695491',updated_at:'2026-08-01'}]}},[key]:{id:'old',resource_type:'baseball_player',resource_id:'695491',_deleted:true,updated_at:'2026-08-10'}}),latest=newestRecord(rows);assert.equal(rows.length,2);assert.equal(latest._deleted,true);assert.match(key,/^atlas_workspace_record_v2_[a-f0-9]{32}$/)});
