import express from 'express';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

const JSON_HEADERS={'Content-Type':'application/json'};
const defaults={
 ai:{primaryEndpoint:'https://openrouter.ai/api/v1',primaryModel:'openrouter/auto',backupEndpoint:'',backupModel:'',primaryKeyCiphertext:null,backupKeyCiphertext:null,instructionSet:'Score public submissions for originality, evidence, clarity, usefulness, and meaningful human-AI collaboration. Penalize spam, copied boilerplate, unsupported certainty, and low-effort repetition.',cadenceMinutes:10,monthlyBudgetUsd:25,spentThisMonthUsd:0,enabled:false,lastRunAt:null,lastError:null},
 economics:{source_name:'Financial Times',source_url:'',source_type:'rss',cadence_hours:12,max_items:20,ai_instruction:'Convert each economic story into a clear decision problem with stakeholders, constraints, tradeoffs, questions, and relevant topics.',enabled:false,last_run_at:null,last_error:null}
};
const scrypt=(password,salt)=>new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(error,key)=>error?reject(error):resolve(key.toString('hex'))));
function storePath(env){return path.resolve(env.ADMIN_STORE_PATH||path.join(process.cwd(),'data','runtime','admin.json'))}
async function readStore(env){try{return JSON.parse(await fs.readFile(storePath(env),'utf8'))}catch(error){if(error.code==='ENOENT')return null;throw error}}
async function writeStore(env,value){const file=storePath(env),temporary=`${file}.${process.pid}.tmp`;await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(temporary,JSON.stringify(value,null,2),{mode:0o600});await fs.rename(temporary,file);return value}
async function authUser(env,fetchImpl,token){if(!token||!env.SUPABASE_URL)return null;const response=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY||env.SUPABASE_SECRET_KEY,Authorization:`Bearer ${token}`}});return response.ok?response.json():null}
async function listUsers(env,fetchImpl,current){if(!env.SUPABASE_SECRET_KEY)return[current];try{const response=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/admin/users?per_page=1000`,{headers:{apikey:env.SUPABASE_SECRET_KEY,Authorization:`Bearer ${env.SUPABASE_SECRET_KEY}`}});if(!response.ok)return[current];const data=await response.json();return data.users||[current]}catch{return[current]}}
function bearer(req){return String(req.get('authorization')||'').replace(/^Bearer\s+/i,'')}
function route(handler){return async(req,res)=>{try{await handler(req,res)}catch(error){console.error(error);res.status(error.status||500).json({error:error.message||'Admin request failed.'})}}}
function keyFrom(store){return crypto.createHash('sha256').update(store.passwordHash).digest()}
function encrypt(secret,store){if(!secret)return null;const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',keyFrom(store),iv),body=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]),tag=cipher.getAuthTag();return`${iv.toString('base64url')}.${tag.toString('base64url')}.${body.toString('base64url')}`}

export function createLocalAdmin({env=process.env,fetchImpl=globalThis.fetch}={}){
 const router=express.Router();
 async function verify(req,{master=false,password=true}={}){const current=await authUser(env,fetchImpl,bearer(req));if(!current)throw Object.assign(new Error('Sign in required.'),{status:401});const store=await readStore(env);if(!store)throw Object.assign(new Error('Administrator has not been initialized.'),{status:409});const role=store.roles?.[current.id];if(!role||master&&role!=='master_admin')throw Object.assign(new Error(master?'Master administrator required.':'Administrator required.'),{status:403});if(password){const provided=String(req.get('x-admin-password')||req.body?.adminPassword||'');if(!provided)throw Object.assign(new Error('Admin password required.'),{status:401});const hash=await scrypt(provided,store.passwordSalt);if(hash!==store.passwordHash)throw Object.assign(new Error('Invalid admin password.'),{status:401})}return{current,role,store}}
 router.get('/api/admin/bootstrap-status',route(async(req,res)=>{const current=await authUser(env,fetchImpl,bearer(req)),store=await readStore(env);res.json({initialized:Boolean(store),signedIn:Boolean(current),role:current&&store?store.roles?.[current.id]||null:null,encryptionConfigured:true,storage:'server-file'})}));
 router.post('/api/admin/bootstrap',route(async(req,res)=>{const current=await authUser(env,fetchImpl,bearer(req));if(!current)throw Object.assign(new Error('Sign in before claiming the first administrator role.'),{status:401});if(await readStore(env))throw Object.assign(new Error('The administrator has already been initialized.'),{status:409});const password=String(req.body?.password||''),repeat=String(req.body?.repeatPassword||'');if(password.length<12)throw Object.assign(new Error('Use an admin password of at least 12 characters.'),{status:400});if(password!==repeat)throw Object.assign(new Error('The passwords do not match.'),{status:400});const passwordSalt=crypto.randomBytes(24).toString('hex'),passwordHash=await scrypt(password,passwordSalt),now=new Date().toISOString();await writeStore(env,{masterUserId:current.id,passwordHash,passwordSalt,roles:{[current.id]:'master_admin'},ai:{...defaults.ai},economics:{...defaults.economics},initializedAt:now,updatedAt:now});res.json({ok:true,role:'master_admin'})}));
 router.get('/api/admin/dashboard',route(async(req,res)=>{const{current,role,store}=await verify(req),users=await listUsers(env,fetchImpl,current),ai={...defaults.ai,...store.ai};res.json({role,masterUserId:store.masterUserId,users:users.map(u=>({id:u.id,email:u.email,createdAt:u.created_at,lastSignInAt:u.last_sign_in_at,role:store.roles?.[u.id]||null})),ai:{...ai,primaryKeyConfigured:Boolean(ai.primaryKeyCiphertext),backupKeyConfigured:Boolean(ai.backupKeyCiphertext)}})}));
 router.patch('/api/admin/users/:id/role',route(async(req,res)=>{const{current,store}=await verify(req,{master:true}),target=req.params.id;if(target===current.id)throw Object.assign(new Error('Transfer master ownership before changing your own role.'),{status:400});const roles={...(store.roles||{})};if(req.body?.role==='admin')roles[target]='admin';else delete roles[target];await writeStore(env,{...store,roles,updatedAt:new Date().toISOString()});res.json({ok:true})}));
 router.post('/api/admin/transfer-master',route(async(req,res)=>{const{current,store}=await verify(req,{master:true}),target=String(req.body?.userId||'');if(!target)throw Object.assign(new Error('Select a user.'),{status:400});const roles={...(store.roles||{}),[target]:'master_admin',[current.id]:'admin'};await writeStore(env,{...store,masterUserId:target,roles,updatedAt:new Date().toISOString()});res.json({ok:true})}));
 router.put('/api/admin/global-ai',route(async(req,res)=>{const{store}=await verify(req),body=req.body||{},old={...defaults.ai,...store.ai},ai={...old,primaryEndpoint:String(body.primaryEndpoint||'https://openrouter.ai/api/v1').replace(/\/$/,''),primaryModel:String(body.primaryModel||'openrouter/auto'),primaryKeyCiphertext:body.primaryKey?encrypt(String(body.primaryKey),store):old.primaryKeyCiphertext,backupEndpoint:String(body.backupEndpoint||'').replace(/\/$/,''),backupModel:String(body.backupModel||''),backupKeyCiphertext:body.backupKey?encrypt(String(body.backupKey),store):old.backupKeyCiphertext,instructionSet:String(body.instructionSet||'').slice(0,12000),cadenceMinutes:Math.max(5,Math.min(1440,Number(body.cadenceMinutes)||10)),monthlyBudgetUsd:Math.max(0,Number(body.monthlyBudgetUsd)||0),enabled:Boolean(body.enabled)};await writeStore(env,{...store,ai,updatedAt:new Date().toISOString()});res.json({ok:true})}));
 router.get('/api/admin/economics/settings',route(async(req,res)=>{const{store}=await verify(req);res.json({settings:{...defaults.economics,...store.economics}})}));
 router.put('/api/admin/economics/settings',route(async(req,res)=>{const{store}=await verify(req),b=req.body||{},economics={...defaults.economics,...store.economics,source_name:String(b.sourceName||'Financial Times'),source_url:String(b.sourceUrl||''),source_type:String(b.sourceType||'rss'),cadence_hours:Math.max(1,Math.min(168,Number(b.cadenceHours)||12)),max_items:Math.max(1,Math.min(50,Number(b.maxItems)||20)),ai_instruction:String(b.aiInstruction||defaults.economics.ai_instruction),enabled:Boolean(b.enabled),last_error:null};await writeStore(env,{...store,economics,updatedAt:new Date().toISOString()});res.json({ok:true})}));
 router.post('/api/admin/run-quality',route(async(req,res)=>{const{store}=await verify(req);res.json(store.ai?.enabled?{ok:true,reviewed:0,estimatedCostUsd:0}:{ok:false,reason:'Global AI disabled'})}));
 return router;
}
