import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createMlbClient } from "./mlb.js";
import { createLegalService } from "./legal.js";
import { gameSlug, renderBaseballGamePage, renderGameNotFoundPage } from "./baseball-game-page.js";
import { playerSlug, renderBaseballPlayerPage } from "./baseball-player-page.js";

const directory=path.dirname(fileURLToPath(import.meta.url));const page=(name)=>path.join(directory,`../public/${name}`);const iso=(d)=>d.toISOString().slice(0,10);
async function previousLineup(teamId,beforeDate){try{const end=new Date(beforeDate||Date.now());end.setUTCDate(end.getUTCDate()-1);const start=new Date(end);start.setUTCDate(start.getUTCDate()-14);const schedule=await fetch(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&teamId=${teamId}&startDate=${iso(start)}&endDate=${iso(end)}`).then(r=>r.ok?r.json():null);const games=(schedule?.dates||[]).flatMap(d=>d.games||[]).sort((a,b)=>String(b.gameDate).localeCompare(String(a.gameDate)));for(const g of games){const box=await fetch(`https://statsapi.mlb.com/api/v1/game/${g.gamePk}/boxscore`).then(r=>r.ok?r.json():null);const side=Number(g.teams?.home?.team?.id)===Number(teamId)?'home':'away',tb=box?.teams?.[side];if(tb?.battingOrder?.length){return tb.battingOrder.map(pid=>{const p=tb.players?.[`ID${pid}`];return p?.person?{id:p.person.id,name:p.person.fullName,position:p.position?.name,seasonStats:p.seasonStats||{}}:null}).filter(Boolean)}}}catch(e){console.warn('Previous lineup unavailable',e.message)}return[]}

export function createApp({mlb=createMlbClient(),legal=createLegalService()}={}){const app=express();app.use(express.json({limit:"32kb"}));
const enrichGame=async(game)=>{const sides=['away','home'];const teamProfiles=await Promise.all(sides.map(s=>game[s]?.id?mlb.getTeam(game[s].id).catch(()=>null):null));game.teamProfiles={away:teamProfiles[0],home:teamProfiles[1]};const ids=sides.map(s=>{const name=game.probablePitchers?.[s]??game[`${s}Pitcher`];return game.teams?.[s]?.pitchers?.find(p=>p.name===name)?.id??game.teams?.[s]?.pitchers?.[0]?.id});const starters=await Promise.all(ids.map(id=>id?mlb.getPlayer(id).catch(()=>null):null));game.starterProfiles={away:starters[0],home:starters[1]};for(const s of sides){if(!game.teams?.[s]?.battingOrder?.length){const fallback=await previousLineup(game[s]?.id,game.date);if(fallback.length){game.teams[s].battingOrder=fallback;game.teams[s].lineupSource='Previous MLB lineup (not confirmed for this game)'}else if(game.teamProfiles?.[s]?.lineup?.players?.length){game.teams[s].battingOrder=game.teamProfiles[s].lineup.players;game.teams[s].lineupSource='Most recently available MLB lineup (not confirmed)'}}else game.teams[s].lineupSource='Confirmed for this game'}return game};
app.get('/api/baseball/search',async(req,res)=>{const q=String(req.query.q??'').trim();if(q.length<2)return res.json({results:[]});try{return res.json({results:await mlb.search(q)})}catch(e){console.error(e);return res.status(502).json({error:'Baseball search is temporarily unavailable.'})}});app.get('/api/baseball/games',async(_req,res)=>{try{return res.json({games:await mlb.getUpcomingGames(14)})}catch(e){console.error(e);return res.status(502).json({error:'Upcoming games are temporarily unavailable.'})}});app.get('/api/baseball/games/:id',async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({error:'Invalid game ID.'});try{const game=await mlb.getGame(req.params.id);return game?res.json({game:await enrichGame(game)}):res.status(404).json({error:'Game not found.'})}catch(e){console.error(e);return res.status(502).json({error:'Game details are temporarily unavailable.'})}});app.get('/api/baseball/teams/:id',async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({error:'Invalid team ID.'});try{const team=await mlb.getTeam(req.params.id);return team?res.json({team}):res.status(404).json({error:'Team not found.'})}catch(e){console.error(e);return res.status(502).json({error:'Team statistics are temporarily unavailable.'})}});app.get('/api/baseball/players',async(req,res)=>{const q=String(req.query.q??'').trim();if(q.length<2)return res.json({players:[]});try{const found=await mlb.search(q);return res.json({players:found.filter(i=>i.type==='player').map(i=>({id:i.id,name:i.name,team:i.subtitle.split(' · ')[0],position:i.subtitle.split(' · ')[1]}))})}catch(e){console.error(e);return res.status(502).json({error:'Player search is temporarily unavailable.'})}});app.get('/api/baseball/players/:id',async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({error:'Invalid player ID.'});try{const player=await mlb.getPlayer(req.params.id);return player?res.json({player}):res.status(404).json({error:'Player not found.'})}catch(e){console.error(e);return res.status(502).json({error:'Player statistics are temporarily unavailable.'})}});
app.get('/api/legal/cases',async(_req,res)=>{try{return res.json({cases:await legal.listCases()})}catch(e){console.error(e);return res.status(500).json({error:'Legal cases are temporarily unavailable.'})}});app.get('/api/legal/cases/:slug',async(req,res)=>{try{const item=await legal.getCase(req.params.slug);return item?res.json(item):res.status(404).json({error:'Case not found.'})}catch(e){console.error(e);return res.status(500).json({error:'Case record is temporarily unavailable.'})}});app.post('/api/legal/cases/:slug/refresh',async(req,res)=>{if(!process.env.LEGAL_ADMIN_TOKEN||req.get('authorization')!==`Bearer ${process.env.LEGAL_ADMIN_TOKEN}`)return res.status(401).json({error:'Unauthorized.'});try{const proposal=await legal.refreshCase(req.params.slug);return proposal?res.json({proposal}):res.status(404).json({error:'Case not found.'})}catch(e){console.error(e);return res.status(502).json({error:e.message})}});
app.get(['/baseball/games/:id','/baseball/games/:id/:slug'],async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(404).type('html').send(renderGameNotFoundPage());try{let game=await mlb.getGame(req.params.id);if(!game)return res.status(404).type('html').send(renderGameNotFoundPage());game=await enrichGame(game);const slug=gameSlug(game),base=(process.env.PUBLIC_APP_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,''),canonicalPath=`/baseball/games/${game.id}/${slug}`;if(req.path!==canonicalPath)return res.redirect(301,canonicalPath);res.set('Cache-Control','public, max-age=60, stale-while-revalidate=300');return res.type('html').send(renderBaseballGamePage(game,`${base}${canonicalPath}`))}catch(e){console.error(e);return res.status(503).type('html').send(renderGameNotFoundPage())}});app.get(['/baseball/players/:id','/baseball/players/:id/:slug'],async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(404).send('Player not found');try{const player=await mlb.getPlayer(req.params.id);if(!player)return res.status(404).send('Player not found');const slug=playerSlug(player),base=(process.env.PUBLIC_APP_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,''),canonicalPath=`/baseball/players/${player.id}/${slug}`;if(req.path!==canonicalPath)return res.redirect(301,canonicalPath);res.set('Cache-Control','public, max-age=120, stale-while-revalidate=600');return res.type('html').send(renderBaseballPlayerPage(player,`${base}${canonicalPath}`))}catch(e){console.error(e);return res.status(503).send('Player temporarily unavailable')}});app.get(['/baseball','/baseball/players','/baseball/{*path}'],(_req,res)=>res.sendFile(page('baseball.html')));app.get('/game/docs',(_req,res)=>res.sendFile(page('game-docs.html')));app.get(['/game','/game/{*path}'],(_req,res)=>res.sendFile(page('game.html')));app.get(['/legal','/legal/{*path}'],(_req,res)=>res.sendFile(page('legal.html')));app.get(['/blog','/blog/{*path}'],(_req,res)=>res.sendFile(page('blog.html')));app.use('/vendor',express.static(path.join(directory,'../node_modules/phaser/dist')));app.use(express.static(path.join(directory,'../public')));app.get('/{*path}',(_req,res)=>res.sendFile(page('index.html')));return app}
