import express from 'express';
import crypto from 'node:crypto';

export const DEFAULT_PRODUCT_TYPES=[
 'Home & Kitchen','Beauty & Personal Care','Pet Supplies','Fitness & Wellness','Travel Accessories','Auto Accessories','Baby & Family','Electronics Accessories','Apparel & Accessories','Hobby & Collectibles','Office & Productivity','Seasonal & Gifts'
];
const DEFAULT_SHARED={version:1,strategies:[],comments:[],fundingInterest:[],contactRequests:[],updatedAt:null};
const clean=(value,max=500)=>String(value??'').trim().slice(0,max);
const list=(value,max=30)=>Array.isArray(value)?value.map(item=>clean(item,80)).filter(Boolean).slice(0,max):String(value||'').split(',').map(item=>clean(item,80)).filter(Boolean).slice(0,max);
const number=value=>value===''||value==null?null:Number.isFinite(Number(value))?Number(value):null;
const validUrl=value=>!value||/^https?:\/\//i.test(value);
function route(handler){return async(req,res)=>{try{await handler(req,res)}catch(error){console.error(error);res.status(error.status||500).json({error:error.message||'Dropshipping request failed.'})}}}
function publicStrategy(row,current){const copy={...row,is_owner:Boolean(current&&row.user_id===current.id)};delete copy.owner_email;return copy}
function initialUser(){return{productTypes:[],savedFilters:{},updatedAt:null}}
function strategyPayload(body,current){
 const productType=clean(body.product_type||body.productType,80),productName=clean(body.product_name||body.productName,160),title=clean(body.title,140),strategyBody=clean(body.strategy_body||body.strategyBody,12000),productUrl=clean(body.product_url||body.productUrl,700);
 if(title.length<3)throw Object.assign(new Error('Enter a strategy title of at least 3 characters.'),{status:400});
 if(productName.length<2)throw Object.assign(new Error('Enter the product being evaluated.'),{status:400});
 if(strategyBody.length<30)throw Object.assign(new Error('Describe the decision thesis in at least 30 characters.'),{status:400});
 if(productUrl&&!validUrl(productUrl))throw Object.assign(new Error('The product or supplier URL must start with http:// or https://.'),{status:400});
 const sellingPrice=number(body.selling_price??body.sellingPrice),supplierCost=number(body.supplier_cost??body.supplierCost),shippingCost=number(body.shipping_cost??body.shippingCost),targetCpa=number(body.target_cpa??body.targetCpa),grossMargin=sellingPrice!=null&&supplierCost!=null?sellingPrice-supplierCost-(shippingCost||0):null;
 return{id:crypto.randomUUID(),user_id:current.id,author_alias:clean(body.author_alias||body.authorAlias||current.user_metadata?.atlas_profile?.username||'Atlas Harbor user',80),title,product_type:productType||'Other',product_name:productName,product_url:productUrl||null,product_notes:clean(body.product_notes||body.productNotes,4000),keywords:list(body.keywords),platform:clean(body.platform||'Other',80),geography:clean(body.geography,180),audience_interests:list(body.audience_interests||body.audienceInterests),bid_strategy:clean(body.bid_strategy||body.bidStrategy,180),budget:number(body.budget),selling_price:sellingPrice,supplier_cost:supplierCost,shipping_cost:shippingCost,target_cpa:targetCpa,gross_margin:grossMargin,test_days:number(body.test_days??body.testDays),success_criteria:clean(body.success_criteria||body.successCriteria,2500),kill_criteria:clean(body.kill_criteria||body.killCriteria,2500),strategy_body:strategyBody,ai_analysis:clean(body.ai_analysis||body.aiAnalysis,12000),results:'',comments_enabled:Boolean(body.comments_enabled??body.commentsEnabled),funding_open:Boolean(body.funding_open??body.fundingOpen),status:'published',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}
}

export function createDropshippingRouter({storage}={}){
 if(!storage)throw new Error('Dropshipping storage is required.');
 const router=express.Router();
 router.get('/api/dropshipping/catalog',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false});let custom=[];if(current)custom=current.user_metadata?.atlas_problem_spaces?.dropshipping?.productTypes||[];res.json({defaults:DEFAULT_PRODUCT_TYPES,custom,all:[...new Set([...DEFAULT_PRODUCT_TYPES,...custom])],storage:storage.configured?'supabase-account-metadata':'unavailable'})}));
 router.post('/api/dropshipping/product-types',route(async(req,res)=>{const name=clean(req.body?.name,80);if(name.length<2)throw Object.assign(new Error('Enter a product type of at least 2 characters.'),{status:400});const result=await storage.writeUser(req,'dropshipping',current=>{const state={...initialUser(),...current},types=Array.isArray(state.productTypes)?state.productTypes:[];state.productTypes=[...new Set([...types,name])].slice(0,80);state.updatedAt=new Date().toISOString();return state});res.status(201).json({productType:name,custom:result.value.productTypes})}));
 router.get('/api/dropshipping/strategies',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false}),shared=await storage.readGlobal('dropshipping',{fallbackCurrent:current,defaults:DEFAULT_SHARED}),query=clean(req.query.q,200).toLowerCase(),category=clean(req.query.category,80).toLowerCase();let rows=(shared.strategies||[]).filter(item=>item.status==='published');if(category&&category!=='all')rows=rows.filter(item=>String(item.product_type||'').toLowerCase()===category);if(query)rows=rows.filter(item=>[item.title,item.product_name,item.product_type,item.platform,item.geography,item.strategy_body,...(item.keywords||[]),...(item.audience_interests||[])].join(' ').toLowerCase().includes(query));rows=rows.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,150).map(item=>publicStrategy(item,current));res.json({strategies:rows,total:rows.length,storage:'supabase-account-metadata'})}));
 router.post('/api/dropshipping/strategies',route(async(req,res)=>{const{current}=await storage.requestUser(req),row=strategyPayload(req.body||{},current);await storage.writeGlobal('dropshipping',shared=>{const state={...DEFAULT_SHARED,...shared},strategies=Array.isArray(state.strategies)?state.strategies:[];state.strategies=[row,...strategies.filter(item=>item.id!==row.id)].slice(0,200);state.updatedAt=new Date().toISOString();return state},{fallbackCurrent:current});res.status(201).json({strategy:publicStrategy(row,current)})}));
 router.get('/api/dropshipping/strategies/:id',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false}),shared=await storage.readGlobal('dropshipping',{fallbackCurrent:current,defaults:DEFAULT_SHARED}),row=(shared.strategies||[]).find(item=>item.id===req.params.id&&item.status==='published');if(!row)throw Object.assign(new Error('Strategy not found.'),{status:404});const comments=row.comments_enabled?(shared.comments||[]).filter(item=>item.strategy_id===row.id).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).slice(-200):[],owner=current?.id===row.user_id,ownerInbox=owner?{funding:(shared.fundingInterest||[]).filter(item=>item.strategy_id===row.id).slice(-100),contacts:(shared.contactRequests||[]).filter(item=>item.strategy_id===row.id).slice(-100)}:null;res.json({strategy:publicStrategy(row,current),comments,ownerInbox})}));
 router.patch('/api/dropshipping/strategies/:id',route(async(req,res)=>{const{current}=await storage.requestUser(req);let updated;await storage.writeGlobal('dropshipping',shared=>{const state={...DEFAULT_SHARED,...shared};state.strategies=(state.strategies||[]).map(item=>{if(item.id!==req.params.id)return item;if(item.user_id!==current.id)throw Object.assign(new Error('Only the creator can update this strategy.'),{status:403});updated={...item,results:req.body?.results===undefined?item.results:clean(req.body.results,12000),comments_enabled:req.body?.comments_enabled===undefined?item.comments_enabled:Boolean(req.body.comments_enabled),funding_open:req.body?.funding_open===undefined?item.funding_open:Boolean(req.body.funding_open),updated_at:new Date().toISOString()};return updated});if(!updated)throw Object.assign(new Error('Strategy not found.'),{status:404});state.updatedAt=new Date().toISOString();return state},{fallbackCurrent:current});res.json({strategy:publicStrategy(updated,current)})}));
 router.post('/api/dropshipping/strategies/:id/comments',route(async(req,res)=>{const{current}=await storage.requestUser(req),body=clean(req.body?.body,5000),alias=clean(req.body?.author_alias||req.body?.authorAlias||current.user_metadata?.atlas_profile?.username||'Atlas Harbor user',80);if(body.length<2)throw Object.assign(new Error('Write a comment before posting.'),{status:400});let comment;await storage.writeGlobal('dropshipping',shared=>{const state={...DEFAULT_SHARED,...shared},strategy=(state.strategies||[]).find(item=>item.id===req.params.id);if(!strategy)throw Object.assign(new Error('Strategy not found.'),{status:404});if(!strategy.comments_enabled)throw Object.assign(new Error('Comments are not enabled for this strategy.'),{status:409});comment={id:crypto.randomUUID(),strategy_id:strategy.id,user_id:current.id,author_alias:alias,body,is_ai_comment:Boolean(req.body?.is_ai_comment),ai_model:clean(req.body?.ai_model,160)||null,created_at:new Date().toISOString()};state.comments=[...(state.comments||[]),comment].slice(-1200);state.updatedAt=new Date().toISOString();return state},{fallbackCurrent:current});res.status(201).json({comment})}));
 router.post('/api/dropshipping/strategies/:id/funding',route(async(req,res)=>{const{current}=await storage.requestUser(req);let interest;await storage.writeGlobal('dropshipping',shared=>{const state={...DEFAULT_SHARED,...shared},strategy=(state.strategies||[]).find(item=>item.id===req.params.id);if(!strategy)throw Object.assign(new Error('Strategy not found.'),{status:404});if(!strategy.funding_open)throw Object.assign(new Error('This creator is not accepting funding interest.'),{status:409});if(strategy.user_id===current.id)throw Object.assign(new Error('This is your strategy.'),{status:400});interest={id:crypto.randomUUID(),strategy_id:strategy.id,user_id:current.id,username:current.user_metadata?.atlas_profile?.username||'Atlas Harbor user',message:clean(req.body?.message,2500),created_at:new Date().toISOString()};state.fundingInterest=[...(state.fundingInterest||[]),interest].slice(-800);state.updatedAt=new Date().toISOString();return state},{fallbackCurrent:current});res.status(201).json({interest})}));
 router.post('/api/dropshipping/strategies/:id/contact',route(async(req,res)=>{const{current}=await storage.requestUser(req),message=clean(req.body?.message,4000);if(message.length<5)throw Object.assign(new Error('Write a short message to the creator.'),{status:400});let request;await storage.writeGlobal('dropshipping',shared=>{const state={...DEFAULT_SHARED,...shared},strategy=(state.strategies||[]).find(item=>item.id===req.params.id);if(!strategy)throw Object.assign(new Error('Strategy not found.'),{status:404});if(strategy.user_id===current.id)throw Object.assign(new Error('This is your strategy.'),{status:400});request={id:crypto.randomUUID(),strategy_id:strategy.id,user_id:current.id,username:current.user_metadata?.atlas_profile?.username||'Atlas Harbor user',message,created_at:new Date().toISOString()};state.contactRequests=[...(state.contactRequests||[]),request].slice(-800);state.updatedAt=new Date().toISOString();return state},{fallbackCurrent:current});res.status(201).json({request})}));
 return router;
}
