import express from 'express';
import crypto from 'node:crypto';
const seed=[
 {slug:'digital-iron-curtain',title:'How should firms operate if the global digital economy fragments?',source_title:'A digital iron curtain is threatening the global economy',source_name:'Financial Times',source_url:'https://www.ft.com/content/90550cee-2dd4-437f-8bda-b1ff41317d23',published_at:'2026-08-03T12:00:00Z',problem:'Companies and governments must decide how much resilience to gain through regionalization without destroying interoperability, cross-border data flows, and productivity.',questions:['Which standards must remain interoperable?','Which supply chains should be localized?','What costs arise from data localization and incompatible cyber rules?'],topics:['digital trade','industrial policy','AI infrastructure','geopolitics']},
 {slug:'yen-intervention',title:'When should governments intervene in currency markets?',source_title:'Team America: Yen police',source_name:'Financial Times',source_url:'https://www.ft.com/content/f6d563ee-9238-4f82-a848-79f2478326bd',published_at:'2026-08-03T12:00:00Z',problem:'US and Japanese authorities face a tradeoff between stabilizing the yen, limiting imported inflation, protecting bond markets, and preserving credible monetary policy.',questions:['Can intervention work without a change in interest-rate policy?','Who bears the cost of a weak yen?','What market behavior would justify coordinated action?'],topics:['foreign exchange','Japan','monetary policy','inflation']},
 {slug:'energy-shock-recession-risk',title:'How should an economy prepare for a prolonged energy-supply shock?',source_title:'Prolonged Iran conflict could tip UK into recession, EY warns',source_name:'The Times',source_url:'https://www.thetimes.com/business/companies-markets/article/prolonged-iran-conflict-could-tip-uk-into-recession-ey-warns-ww5htrlqf',published_at:'2026-08-03T12:00:00Z',problem:'Policymakers and firms must choose how to absorb a possible oil and gas shock while limiting recession, inflation, and damage to household purchasing power.',questions:['Which sectors need temporary support?','How should central banks react to supply-driven inflation?','What investments reduce exposure before the next disruption?'],topics:['energy','recession','UK economy','inflation']}
];
const safe=async r=>{const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||d?.error||t||`Request failed (${r.status})`);return d};
const scrypt=(p,s)=>new Promise((ok,no)=>crypto.scrypt(p,s,64,(e,k)=>e?no(e):ok(k.toString('hex'))));
const slug=v=>String(v||'problem').toLowerCase().replace(/<[^>]+>/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
const text=v=>String(v||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(block,name)=>text(block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]||'');
function parseFeed(xml,limit){const blocks=[...(xml.match(/<item[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry[\s\S]*?<\/entry>/gi)||[])];return blocks.slice(0,limit).map(b=>{const title=tag(b,'title'),link=tag(b,'link')||b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||'',description=tag(b,'description')||tag(b,'summary')||tag(b,'content'),published=tag(b,'pubDate')||tag(b,'published')||tag(b,'updated');return{title,link,description,published}}).filter(x=>x.title&&x.link)}
function decrypt(value,env){if(!value||!env.ADMIN_ENCRYPTION_KEY)return null;const key=crypto.createHash('sha256').update(env.ADMIN_ENCRYPTION_KEY).digest(),[a,b,c]=value.split('.').map(x=>Buffer.from(x,'base64url')),d=crypto.createDecipheriv('aes-256-gcm',key,a);d.setAuthTag(b);return Buffer.concat([d.update(c),d.final()]).toString('utf8')}
export function createEconomicsRouter({env=process.env,fetchImpl=globalThis.fetch}={}){const r=express.Router(),enabled=Boolean(env.SUPABASE_URL&&env.SUPABASE_SECRET_KEY),headers=enabled?{apikey:env.SUPABASE_SECRET_KEY,Authorization:`Bearer ${env.SUPABASE_SECRET_KEY}`,'Content-Type':'application/json'}:{},rest=(p,o={})=>safe(fetchImpl(`${env.SUPABASE_URL}/rest/v1/${p}`,{...o,headers:{...headers,...o.headers}}));let timer;
 async function admin(req){const token=String(req.get('authorization')||'').replace(/^Bearer\s+/i,''),pw=String(req.get('x-admin-password')||req.body?.adminPassword||'');if(!token||!pw)throw Object.assign(new Error('Administrator sign-in and password are required.'),{status:401});const u=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});if(!u.ok)throw Object.assign(new Error('Sign in required.'),{status:401});const user=await u.json(),roles=await rest(`admin_roles?user_id=eq.${user.id}&select=role`);if(!roles?.length)throw Object.assign(new Error('Administrator required.'),{status:403});const sys=(await rest('admin_system?singleton=eq.true&select=password_hash,password_salt'))?.[0],hash=await scrypt(pw,sys.password_salt);if(hash!==sys.password_hash)throw Object.assign(new Error('Invalid admin password.'),{status:401})}
 async function callAI(settings,item,instruction){const ai=(await rest('global_ai_settings?singleton=eq.true&select=*'))?.[0];for(const p of [{endpoint:ai?.primary_endpoint,model:ai?.primary_model,key:decrypt(ai?.primary_key_ciphertext,env)},{endpoint:ai?.backup_endpoint,model:ai?.backup_model,key:decrypt(ai?.backup_key_ciphertext,env)}]){if(!p.endpoint||!p.model||!p.key)continue;try{const response=await fetchImpl(`${p.endpoint.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${p.key}`,'Content-Type':'application/json'},body:JSON.stringify({model:p.model,temperature:.1,response_format:{type:'json_object'},messages:[{role:'system',content:'Return strict JSON only with title, problem, questions (array), and topics (array). Do not reproduce article text.'},{role:'user',content:`${instruction}\nSource: ${settings.source_name}\nHeadline: ${item.title}\nFeed summary: ${item.description.slice(0,2500)}\nURL: ${item.link}`}]})});const data=await safe(response),parsed=JSON.parse(data.choices?.[0]?.message?.content||'{}');return{...parsed,model:data.model||p.model}}catch(e){console.error('Economics AI provider failed',e)}}throw new Error('No configured global AI provider responded.')}
 async function run(){if(!enabled)return{ok:false,reason:'Supabase unavailable'};const settings=(await rest('economics_feed_settings?singleton=eq.true&select=*'))?.[0];if(!settings?.enabled||!settings.source_url)return{ok:false,reason:'Economics feed disabled or missing URL'};try{const response=await fetchImpl(settings.source_url,{headers:{Accept:'application/rss+xml,application/atom+xml,application/xml,text/xml,application/json;q=.8,*/*;q=.5','User-Agent':'AtlasHarbor/1.0'}});if(!response.ok)throw new Error(`Feed returned ${response.status}`);const raw=await response.text();let items=[];if(settings.source_type==='json'){const data=JSON.parse(raw),list=Array.isArray(data)?data:data.items||data.articles||[];items=list.slice(0,settings.max_items).map(x=>({title:x.title,link:x.url||x.link,description:x.description||x.summary||'',published:x.published_at||x.pubDate}))}else items=parseFeed(raw,settings.max_items);let added=0;for(const item of items){const id=slug(`${item.title}-${item.link}`);const exists=await rest(`economic_problems?slug=eq.${encodeURIComponent(id)}&select=id&limit=1`);if(exists?.length)continue;const out=await callAI(settings,item,settings.ai_instruction);await rest('economic_problems',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({slug:id,title:String(out.title||item.title).slice(0,240),problem:String(out.problem||'').slice(0,6000),questions:Array.isArray(out.questions)?out.questions.slice(0,12):[],topics:Array.isArray(out.topics)?out.topics.slice(0,20):[],source_title:item.title,source_name:settings.source_name,source_url:item.link,source_published_at:item.published?new Date(item.published).toISOString():null,published_at:new Date().toISOString(),status:'published',ai_model:out.model})});added++}await rest('economics_feed_settings?singleton=eq.true',{method:'PATCH',body:JSON.stringify({last_run_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()})});return{ok:true,added,seen:items.length}}catch(e){await rest('economics_feed_settings?singleton=eq.true',{method:'PATCH',body:JSON.stringify({last_run_at:new Date().toISOString(),last_error:e.message,updated_at:new Date().toISOString()})}).catch(()=>{});throw e}}
 async function schedule(){if(timer)clearInterval(timer);if(!enabled)return;try{const s=(await rest('economics_feed_settings?singleton=eq.true&select=enabled,cadence_hours'))?.[0];if(!s?.enabled)return;timer=setInterval(()=>run().catch(console.error),Math.max(1,Number(s.cadence_hours)||12)*3600000);timer.unref?.()}catch(e){console.error('Economics scheduler unavailable',e)}}
 r.get('/api/economics/problems',async(_q,res)=>{try{if(!enabled)return res.json({problems:seed,source:'manual-seed'});const rows=await rest('economic_problems?status=eq.published&select=*&order=published_at.desc&limit=100');res.json({problems:rows?.length?rows:seed,source:rows?.length?'database':'manual-seed'})}catch(e){res.json({problems:seed,source:'manual-seed',warning:e.message})}});
 r.get('/api/admin/economics/settings',async(req,res)=>{try{await admin(req);res.json({settings:(await rest('economics_feed_settings?singleton=eq.true&select=*'))?.[0]})}catch(e){res.status(e.status||500).json({error:e.message})}});
 r.put('/api/admin/economics/settings',async(req,res)=>{try{await admin(req);const b=req.body||{},row={source_name:String(b.sourceName||'Financial Times'),source_url:String(b.sourceUrl||''),source_type:String(b.sourceType||'rss'),cadence_hours:Math.max(1,Math.min(168,Number(b.cadenceHours)||12)),max_items:Math.max(1,Math.min(50,Number(b.maxItems)||20)),ai_instruction:String(b.aiInstruction||'Convert each economic story into a clear decision problem with stakeholders, constraints, tradeoffs, questions, and relevant topics.'),enabled:Boolean(b.enabled),updated_at:new Date().toISOString()};await rest('economics_feed_settings?singleton=eq.true',{method:'PATCH',body:JSON.stringify(row)});await schedule();res.json({ok:true})}catch(e){res.status(e.status||500).json({error:e.message})}});
 r.post('/api/admin/economics/run',async(req,res)=>{try{await admin(req);res.json(await run())}catch(e){res.status(e.status||500).json({error:e.message})}});
 schedule();return r}
