import express from 'express';
import crypto from 'node:crypto';
import {DEFAULT_ECONOMICS} from './economics-service.js';
const seed=[
 {slug:'digital-iron-curtain',title:'How should firms operate if the global digital economy fragments?',source_title:'A digital iron curtain is threatening the global economy',source_name:'Financial Times',source_url:'https://www.ft.com/content/90550cee-2dd4-437f-8bda-b1ff41317d23',published_at:'2026-08-03T12:00:00Z',problem:'Companies and governments must decide how much resilience to gain through regionalization without destroying interoperability, cross-border data flows, and productivity.',questions:['Which standards must remain interoperable?','Which supply chains should be localized?','What costs arise from data localization and incompatible cyber rules?'],topics:['digital trade','industrial policy','AI infrastructure','geopolitics']},
 {slug:'yen-intervention',title:'When should governments intervene in currency markets?',source_title:'Team America: Yen police',source_name:'Financial Times',source_url:'https://www.ft.com/content/f6d563ee-9238-4f82-a848-79f2478326bd',published_at:'2026-08-03T12:00:00Z',problem:'US and Japanese authorities face a tradeoff between stabilizing the yen, limiting imported inflation, protecting bond markets, and preserving credible monetary policy.',questions:['Can intervention work without a change in interest-rate policy?','Who bears the cost of a weak yen?','What market behavior would justify coordinated action?'],topics:['foreign exchange','Japan','monetary policy','inflation']}
];
const scrypt=(password,salt)=>new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(error,key)=>error?reject(error):resolve(key.toString('hex'))));
const route=handler=>async(req,res)=>{try{await handler(req,res)}catch(error){console.error(error);res.status(error.status||500).json({error:error.message||'Economics request failed.'})}};
export function createEconomicsRouter({service,storage}={}){
 if(!service||!storage)throw new Error('Economics service and storage are required.');
 const router=express.Router();
 async function verifyAdmin(req){const{current}=await storage.requestUser(req),config=current.user_metadata?.atlas_admin,role=config?.roles?.[current.id];if(!config)throw Object.assign(new Error('Administrator has not been initialized.'),{status:409});if(!role)throw Object.assign(new Error('Administrator required.'),{status:403});const password=String(req.get('x-admin-password')||req.body?.adminPassword||'');if(!password)throw Object.assign(new Error('Admin password required.'),{status:401});const hash=await scrypt(password,config.passwordSalt);if(hash!==config.passwordHash)throw Object.assign(new Error('Invalid admin password.'),{status:401});return{current,config,role}}
 router.get('/api/economics/problems',route(async(_req,res)=>{const current=await service.status(),rows=current.settings?.problems||[];res.json({problems:rows.length?rows:seed,source:rows.length?'account-metadata-feed':'manual-seed',lastRunAt:current.settings?.last_run_at||null,lastError:current.settings?.last_error||null})}));
 router.get('/api/economics/status',route(async(_req,res)=>{const current=await service.status(),settings=current.settings||{};res.set('Cache-Control','no-store');res.json({configured:current.configured,enabled:Boolean(settings.enabled),sourceName:settings.source_name,sourceUrlConfigured:Boolean(settings.source_url),lastStartedAt:settings.last_started_at,lastRunAt:settings.last_run_at,lastError:settings.last_error,currentRun:settings.current_run,lastResult:settings.last_result,runLog:(settings.run_log||[]).slice(0,10),storyCount:(settings.problems||[]).length,storage:current.storage})}));
 router.post('/api/economics/run',route(async(_req,res)=>{const accepted=await service.trigger({trigger:'public-api'});res.status(202).json(accepted)}));
 router.get('/api/admin/economics/settings',route(async(req,res)=>{await verifyAdmin(req);const current=await service.status();res.json({settings:current.settings})}));
 router.put('/api/admin/economics/settings',route(async(req,res)=>{const{current}=await verifyAdmin(req),body=req.body||{};await storage.updateHost(metadata=>{const admin={...(metadata.atlas_admin||{})},old={...DEFAULT_ECONOMICS,...(admin.economics||{})};admin.economics={...old,source_name:String(body.sourceName||'Financial Times').slice(0,160),source_url:String(body.sourceUrl||'').trim().slice(0,1200),source_type:['rss','atom','json','manual'].includes(String(body.sourceType))?String(body.sourceType):'rss',cadence_hours:Math.max(1,Math.min(168,Number(body.cadenceHours)||12)),max_items:Math.max(1,Math.min(50,Number(body.maxItems)||8)),ai_items_per_run:Math.max(1,Math.min(9,Number(body.aiItemsPerRun)||old.ai_items_per_run||6)),ai_instruction:String(body.aiInstruction||DEFAULT_ECONOMICS.ai_instruction).slice(0,12000),enabled:Boolean(body.enabled),last_error:null};return{...metadata,atlas_admin:admin}},{fallbackCurrent:current});res.json({ok:true})}));
 router.post('/api/admin/economics/run',route(async(req,res)=>{await verifyAdmin(req);const accepted=await service.trigger({trigger:'admin'});res.status(202).json(accepted)}));
 return router;
}
