import express from 'express';
import crypto from 'node:crypto';
const seed=[
 {slug:'digital-iron-curtain',title:'How should firms operate if the global digital economy fragments?',source_title:'A digital iron curtain is threatening the global economy',source_name:'Financial Times',source_url:'https://www.ft.com/content/90550cee-2dd4-437f-8bda-b1ff41317d23',published_at:'2026-08-03T12:00:00Z',problem:'Companies and governments must decide how much resilience to gain through regionalization without destroying interoperability, cross-border data flows, and productivity.',questions:['Which standards must remain interoperable?','Which supply chains should be localized?','What costs arise from data localization and incompatible cyber rules?'],topics:['digital trade','industrial policy','AI infrastructure','geopolitics']},
 {slug:'yen-intervention',title:'When should governments intervene in currency markets?',source_title:'Team America: Yen police',source_name:'Financial Times',source_url:'https://www.ft.com/content/f6d563ee-9238-4f82-a848-79f2478326bd',published_at:'2026-08-03T12:00:00Z',problem:'US and Japanese authorities face a tradeoff between stabilizing the yen, limiting imported inflation, protecting bond markets, and preserving credible monetary policy.',questions:['Can intervention work without a change in interest-rate policy?','Who bears the cost of a weak yen?','What market behavior would justify coordinated action?'],topics:['foreign exchange','Japan','monetary policy','inflation']},
 {slug:'energy-shock-recession-risk',title:'How should an economy prepare for a prolonged energy-supply shock?',source_title:'Prolonged Iran conflict could tip UK into recession, EY warns',source_name:'The Times',source_url:'https://www.thetimes.com/business/companies-markets/article/prolonged-iran-conflict-could-tip-uk-into-recession-ey-warns-ww5htrlqf',published_at:'2026-08-03T12:00:00Z',problem:'Policymakers and firms must choose how to absorb a possible oil and gas shock while limiting recession, inflation, and damage to household purchasing power.',questions:['Which sectors need temporary support?','How should central banks react to supply-driven inflation?','What investments reduce exposure before the next disruption?'],topics:['energy','recession','UK economy','inflation']}
];
const safe=async r=>{const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||d?.error||t||`Request failed (${r.status})`);return d};
const scrypt=(p,s)=>new Promise((ok,no)=>crypto.scrypt(p,s,64,(e,k)=>e?no(e):ok(k.toString('hex'))));
export function createEconomicsRouter({env=process.env,fetchImpl=globalThis.fetch}={}){const r=express.Router(),enabled=Boolean(env.SUPABASE_URL&&env.SUPABASE_SECRET_KEY),headers=enabled?{apikey:env.SUPABASE_SECRET_KEY,Authorization:`Bearer ${env.SUPABASE_SECRET_KEY}`,'Content-Type':'application/json'}:{};const rest=(p,o={})=>safe(fetchImpl(`${env.SUPABASE_URL}/rest/v1/${p}`,{...o,headers:{...headers,...o.headers}}));
 async function admin(req){const token=String(req.get('authorization')||'').replace(/^Bearer\s+/i,''),pw=String(req.get('x-admin-password')||req.body?.adminPassword||'');if(!token||!pw)throw Object.assign(new Error('Administrator sign-in and password are required.'),{status:401});const u=await fetchImpl(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});if(!u.ok)throw Object.assign(new Error('Sign in required.'),{status:401});const user=await u.json(),roles=await rest(`admin_roles?user_id=eq.${user.id}&select=role`);if(!roles?.length)throw Object.assign(new Error('Administrator required.'),{status:403});const sys=(await rest('admin_system?singleton=eq.true&select=password_hash,password_salt'))?.[0],hash=await scrypt(pw,sys.password_salt);if(hash!==sys.password_hash)throw Object.assign(new Error('Invalid admin password.'),{status:401});}
 r.get('/api/economics/problems',async(_q,res)=>{try{if(!enabled)return res.json({problems:seed,source:'manual-seed'});const rows=await rest('economic_problems?status=eq.published&select=*&order=published_at.desc&limit=100');res.json({problems:rows?.length?rows:seed,source:rows?.length?'database':'manual-seed'})}catch(e){res.json({problems:seed,source:'manual-seed',warning:e.message})}});
 r.get('/api/admin/economics/settings',async(req,res)=>{try{await admin(req);res.json({settings:(await rest('economics_feed_settings?singleton=eq.true&select=*'))?.[0]})}catch(e){res.status(e.status||500).json({error:e.message})}});
 r.put('/api/admin/economics/settings',async(req,res)=>{try{await admin(req);const b=req.body||{},row={source_name:String(b.sourceName||'Financial Times'),source_url:String(b.sourceUrl||''),source_type:String(b.sourceType||'rss'),cadence_hours:Math.max(1,Math.min(168,Number(b.cadenceHours)||12)),max_items:Math.max(1,Math.min(50,Number(b.maxItems)||20)),ai_instruction:String(b.aiInstruction||'Convert each economic story into a clear decision problem with stakeholders, constraints, tradeoffs, questions, and relevant topics.'),enabled:Boolean(b.enabled),updated_at:new Date().toISOString()};await rest('economics_feed_settings?singleton=eq.true',{method:'PATCH',body:JSON.stringify(row)});res.json({ok:true})}catch(e){res.status(e.status||500).json({error:e.message})}});
 return r}
