import express from 'express';
const ua='AtlasHarbor/1.0 (restaurant discovery; contact via repository)';
const clean=v=>String(v||'').trim().slice(0,180);
async function json(url,options={}){const r=await fetch(url,{...options,headers:{'User-Agent':ua,Accept:'application/json',...(options.headers||{})},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Source returned ${r.status}`);return r.json()}
export function createFoodRouter(){const router=express.Router();
 router.get('/search',async(req,res)=>{const location=clean(req.query.location),query=clean(req.query.q||'restaurant');if(!location)return res.status(400).json({error:'Location is required.'});try{const places=await json(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&addressdetails=1&q=${encodeURIComponent(location)}`);const place=places[0];if(!place)return res.json({location:null,restaurants:[]});const lat=Number(place.lat),lon=Number(place.lon),radius=Math.min(10000,Math.max(1000,Number(req.query.radius)||5000));const overpass=`[out:json][timeout:20];(nwr[amenity=restaurant](around:${radius},${lat},${lon});nwr[amenity=cafe](around:${radius},${lat},${lon}););out center tags 80;`;const osm=await json('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`data=${encodeURIComponent(overpass)}`});let restaurants=(osm.elements||[]).map(x=>({id:`osm-${x.type}-${x.id}`,name:x.tags?.name||x.tags?.['name:en']||'Unnamed restaurant',cuisine:x.tags?.cuisine||null,address:[x.tags?.['addr:housenumber'],x.tags?.['addr:street'],x.tags?.['addr:city']].filter(Boolean).join(' ')||null,lat:x.lat||x.center?.lat,lon:x.lon||x.center?.lon,website:x.tags?.website||x.tags?.['contact:website']||null,phone:x.tags?.phone||x.tags?.['contact:phone']||null,openingHours:x.tags?.opening_hours||null,source:'OpenStreetMap'})).filter(x=>!query||`${x.name} ${x.cuisine||''}`.toLowerCase().includes(query.toLowerCase())||query.toLowerCase()==='restaurant').slice(0,60);
 if(process.env.GOOGLE_PLACES_API_KEY){try{const g=await json('https://places.googleapis.com/v1/places:searchText',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':process.env.GOOGLE_PLACES_API_KEY,'X-Goog-FieldMask':'places.id,places.displayName,places.formattedAddress,places.location,places.rating,places.userRatingCount,places.priceLevel,places.primaryTypeDisplayName,places.googleMapsUri,places.regularOpeningHours,places.reviews,places.reviewSummary'},body:JSON.stringify({textQuery:`${query} restaurants in ${location}`,maxResultCount:20})});restaurants=(g.places||[]).map(p=>({id:`google-${p.id}`,providerId:p.id,name:p.displayName?.text,address:p.formattedAddress,lat:p.location?.latitude,lon:p.location?.longitude,rating:p.rating,reviewCount:p.userRatingCount,priceLevel:p.priceLevel,type:p.primaryTypeDisplayName?.text,mapsUrl:p.googleMapsUri,openingHours:p.regularOpeningHours?.weekdayDescriptions,reviews:(p.reviews||[]).slice(0,5).map(r=>({author:r.authorAttribution?.displayName,rating:r.rating,text:r.text?.text,published:r.relativePublishTimeDescription,uri:r.googleMapsUri})),reviewSummary:p.reviewSummary?.text?.text,reviewSummaryDisclosure:p.reviewSummary?.disclosureText?.text,reviewSummaryUri:p.reviewSummary?.reviewsUri,source:'Google Places'}));}catch(e){console.warn('Google Places enrichment failed',e.message)}}
 return res.json({location:{name:place.display_name,lat,lon,country:place.address?.country,countryCode:place.address?.country_code},restaurants,reviewProvider:process.env.GOOGLE_PLACES_API_KEY?'google':'community-only',attribution:['© OpenStreetMap contributors',...(process.env.GOOGLE_PLACES_API_KEY?['Google Places']:[])]});}catch(e){console.error(e);return res.status(502).json({error:'Restaurant discovery is temporarily unavailable.'})}});
 return router}
