import express from 'express';
import crypto from 'node:crypto';
import {createProblemSpaceStorage} from './problem-space-storage.js';
import {solveFoodDecision} from './food-decision.js';

const UA='AtlasHarbor/1.0 (restaurant decision planner; contact via repository)';
const GOOGLE_BASE='https://places.googleapis.com/v1';
const FOOD_SPACE='food_planner';
const DEFAULT_PROFILE={location:null,participants:[{id:'you',name:'You',likes:[],avoids:[],dietary:[],spice:50,adventurousness:50,noise:'any',maxPrice:null}],defaults:{occasion:'meal',maxDistanceKm:10,maxPrice:null,openNow:false,freshnessPriority:'normal',rawShellfish:false},decisions:[]};
const clean=(value,max=240)=>String(value||'').trim().slice(0,max);
const number=(value,fallback=null)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback};
const route=handler=>async(req,res)=>{try{await handler(req,res)}catch(error){console.error(error);res.status(error.status||500).json({error:error.message||'Food decision request failed.'})}};

async function readJson(fetchImpl,url,options={}){
 const response=await fetchImpl(url,{...options,headers:{'User-Agent':UA,Accept:'application/json',...(options.headers||{})},signal:AbortSignal.timeout(options.timeout||18000)}),body=await response.text();let data=null;try{data=body?JSON.parse(body):null}catch{}
 if(!response.ok){const error=new Error(data?.error?.message||data?.message||body||`Source returned ${response.status}`);error.status=response.status;throw error}return data;
}
function distanceKm(a,b){if(!a||!b)return null;const rad=value=>value*Math.PI/180,R=6371,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),lat1=rad(a.latitude),lat2=rad(b.latitude),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function adjustedRating(rating,count,average=4.1,confidence=50){const r=number(rating,average),n=Math.max(0,number(count,0));return(n/(n+confidence))*r+(confidence/(n+confidence))*average}
function priceNumber(level){return({PRICE_LEVEL_FREE:0,PRICE_LEVEL_INEXPENSIVE:1,PRICE_LEVEL_MODERATE:2,PRICE_LEVEL_EXPENSIVE:3,PRICE_LEVEL_VERY_EXPENSIVE:4})[level]??null}
function priceLabel(level){return({PRICE_LEVEL_FREE:'Free',PRICE_LEVEL_INEXPENSIVE:'$',PRICE_LEVEL_MODERATE:'$$',PRICE_LEVEL_EXPENSIVE:'$$$',PRICE_LEVEL_VERY_EXPENSIVE:'$$$$'})[level]||null}
function closingSoon(place){const next=place.currentOpeningHours?.nextCloseTime;if(!next)return false;const minutes=(new Date(next).getTime()-Date.now())/60000;return minutes>0&&minutes<20}
function mapGooglePlace(place,center){const location=place.location?{latitude:place.location.latitude,longitude:place.location.longitude}:null;return{id:`google-${place.id}`,providerId:place.id,name:place.displayName?.text||'Unnamed restaurant',address:place.formattedAddress||place.shortFormattedAddress||null,location,lat:location?.latitude,lon:location?.longitude,distanceKm:distanceKm(center,location),rating:place.rating||null,reviewCount:place.userRatingCount||0,priceLevel:place.priceLevel||null,priceNumber:priceNumber(place.priceLevel),priceLabel:priceLabel(place.priceLevel),primaryType:place.primaryType||null,primaryTypeDisplay:place.primaryTypeDisplayName?.text||null,types:place.types||[],businessStatus:place.businessStatus||null,currentOpeningHours:place.currentOpeningHours||null,regularOpeningHours:place.regularOpeningHours||null,website:place.websiteUri||null,phone:place.nationalPhoneNumber||place.internationalPhoneNumber||null,mapsUrl:place.googleMapsUri||null,takeout:place.takeout,dineIn:place.dineIn,delivery:place.delivery,reservable:place.reservable,servesVegetarianFood:place.servesVegetarianFood,outdoorSeating:place.outdoorSeating,goodForGroups:place.goodForGroups,restroom:place.restroom,reviews:(place.reviews||[]).slice(0,5).map(review=>({author:review.authorAttribution?.displayName,rating:review.rating,text:review.text?.text||review.originalText?.text,published:review.relativePublishTimeDescription,uri:review.googleMapsUri})),source:'Google Places',closingSoon:closingSoon(place),adjustedRating:adjustedRating(place.rating,place.userRatingCount)}}

async function googleAutocomplete(fetchImpl,input,key,sessionToken){const body={input,includeQueryPredictions:false};if(sessionToken)body.sessionToken=sessionToken;const data=await readJson(fetchImpl,`${GOOGLE_BASE}/places:autocomplete`,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key},body:JSON.stringify(body)});return(data.suggestions||[]).map(item=>item.placePrediction).filter(Boolean).map(prediction=>({placeId:prediction.placeId,text:prediction.text?.text||'',primaryText:prediction.structuredFormat?.mainText?.text||'',secondaryText:prediction.structuredFormat?.secondaryText?.text||'',types:prediction.types||[]}))}
async function googlePlaceLocation(fetchImpl,placeId,key){return readJson(fetchImpl,`${GOOGLE_BASE}/places/${encodeURIComponent(placeId)}`,{headers:{'X-Goog-Api-Key':key,'X-Goog-FieldMask':'id,displayName,formattedAddress,location,types'}})}
async function googleSearch(fetchImpl,{query,center,locationText,openNow,maxResults,radiusMeters=15000,key}){const mask=['places.id','places.displayName','places.formattedAddress','places.location','places.rating','places.userRatingCount','places.priceLevel','places.businessStatus','places.currentOpeningHours','places.regularOpeningHours','places.primaryType','places.primaryTypeDisplayName','places.types','places.googleMapsUri','places.websiteUri','places.nationalPhoneNumber','places.internationalPhoneNumber','places.takeout','places.dineIn','places.delivery','places.reservable','places.servesVegetarianFood','places.outdoorSeating','places.goodForGroups','places.restroom','places.reviews'].join(','),body={textQuery:locationText?`${query} in ${locationText}`:query,maxResultCount:Math.min(20,Math.max(1,maxResults||20)),languageCode:'en'};if(center)body.locationBias={circle:{center,radius:Math.min(50000,Math.max(1000,Number(radiusMeters)||15000))}};if(openNow)body.openNow=true;const data=await readJson(fetchImpl,`${GOOGLE_BASE}/places:searchText`,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':mask},body:JSON.stringify(body)});return data.places||[]}
async function reverseLocation(fetchImpl,latitude,longitude){const data=await readJson(fetchImpl,`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(latitude)}&lon=${encodeURIComponent(longitude)}&zoom=18&addressdetails=1`);return{name:data.display_name||'Selected map location',address:data.display_name||null,latitude:Number(latitude),longitude:Number(longitude),city:data.address?.city||data.address?.town||data.address?.village||null,country:data.address?.country||null,countryCode:data.address?.country_code||null,provider:'OpenStreetMap Nominatim'}}
async function fallbackAround(fetchImpl,{center,query,radius}){const lat=center.latitude,lon=center.longitude,overpass=`[out:json][timeout:20];(nwr[amenity=restaurant](around:${radius},${lat},${lon});nwr[amenity=cafe](around:${radius},${lat},${lon});nwr[amenity=fast_food](around:${radius},${lat},${lon}););out center tags 100;`,osm=await readJson(fetchImpl,'https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`data=${encodeURIComponent(overpass)}`});return(osm.elements||[]).map(item=>{const latitude=item.lat||item.center?.lat,longitude=item.lon||item.center?.lon,location={latitude,longitude},name=item.tags?.name||item.tags?.['name:en']||'Unnamed restaurant',cuisine=item.tags?.cuisine||'';return{id:`osm-${item.type}-${item.id}`,name,address:[item.tags?.['addr:housenumber'],item.tags?.['addr:street'],item.tags?.['addr:city']].filter(Boolean).join(' ')||null,location,lat:latitude,lon:longitude,distanceKm:distanceKm(center,location),primaryType:cuisine||item.tags?.amenity||null,primaryTypeDisplay:cuisine||item.tags?.amenity||null,types:[item.tags?.amenity,cuisine].filter(Boolean),website:item.tags?.website||item.tags?.['contact:website']||null,phone:item.tags?.phone||item.tags?.['contact:phone']||null,currentOpeningHours:null,regularOpeningHours:item.tags?.opening_hours||null,source:'OpenStreetMap',reviewCount:0,rating:null,priceNumber:null,priceLabel:null,reviews:[],servesVegetarianFood:/yes|only/i.test(item.tags?.['diet:vegetarian']||'')?true:null,goodForGroups:null,businessStatus:'OPERATIONAL',closingSoon:false,adjustedRating:null}}).filter(place=>!query||query==='restaurant'||`${place.name} ${place.primaryType||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,80)}
async function applyRoadDistances(fetchImpl,center,places){
 const candidates=places.filter(place=>Number.isFinite(Number(place.lat))&&Number.isFinite(Number(place.lon))).slice(0,20);
 if(!candidates.length)return{places,provider:'unavailable'};
 const coordinates=[[center.longitude,center.latitude],...candidates.map(place=>[place.lon,place.lat])].map(pair=>pair.join(',')).join(';');
 try{
  const data=await readJson(fetchImpl,`https://router.project-osrm.org/table/v1/driving/${coordinates}?sources=0&annotations=distance,duration`,{timeout:12000}),distances=data.distances?.[0]||[],durations=data.durations?.[0]||[],byId=new Map(candidates.map((place,index)=>[place.id,{distance:distances[index+1],duration:durations[index+1]}]));
  return{provider:'osrm-openstreetmap',places:places.map(place=>{const route=byId.get(place.id);return route&&Number.isFinite(route.distance)?{...place,aerialDistanceKm:place.distanceKm,distanceKm:route.distance/1000,routeDurationMinutes:Number.isFinite(route.duration)?Math.round(route.duration/60):null,travelDistanceSource:'osrm-openstreetmap'}:{...place,travelDistanceSource:'straight-line-fallback'}})};
 }catch{return{provider:'straight-line-fallback',places:places.map(place=>({...place,travelDistanceSource:'straight-line-fallback'}))}}
}
function queryFrom(body){const direct=clean(body.query||'');if(direct)return direct;const likes=(body.participants||[]).flatMap(person=>Array.isArray(person.likes)?person.likes:[]).filter(Boolean);return likes.length?`${[...new Set(likes)].slice(0,4).join(' or ')} restaurant`:'restaurant'}
function sanitizeProfile(body={}){const location=body.location&&Number.isFinite(Number(body.location.latitude))&&Number.isFinite(Number(body.location.longitude))?{name:clean(body.location.name||body.location.address||'Saved location'),address:clean(body.location.address||'',500),latitude:Number(body.location.latitude),longitude:Number(body.location.longitude),placeId:clean(body.location.placeId||'',220)||null}:null,participants=(Array.isArray(body.participants)?body.participants:DEFAULT_PROFILE.participants).slice(0,10).map((person,index)=>({id:clean(person.id||`person-${index+1}`,80),name:clean(person.name||`Person ${index+1}`,80),likes:(Array.isArray(person.likes)?person.likes:[]).map(item=>clean(item,60)).filter(Boolean).slice(0,12),avoids:(Array.isArray(person.avoids)?person.avoids:[]).map(item=>clean(item,60)).filter(Boolean).slice(0,12),dietary:(Array.isArray(person.dietary)?person.dietary:[]).map(item=>clean(item,40)).filter(Boolean).slice(0,10),spice:Math.max(0,Math.min(100,number(person.spice,50))),adventurousness:Math.max(0,Math.min(100,number(person.adventurousness,50))),noise:['any','quiet','lively'].includes(person.noise)?person.noise:'any',maxPrice:person.maxPrice==null||person.maxPrice===''?null:Math.max(0,Math.min(4,number(person.maxPrice,4)))})),defaults={occasion:clean(body.defaults?.occasion||'meal',80),maxDistanceKm:Math.max(1,Math.min(80,number(body.defaults?.maxDistanceKm,10))),maxPrice:body.defaults?.maxPrice==null||body.defaults?.maxPrice===''?null:Math.max(0,Math.min(4,number(body.defaults.maxPrice,4))),openNow:Boolean(body.defaults?.openNow),freshnessPriority:['normal','high'].includes(body.defaults?.freshnessPriority)?body.defaults.freshnessPriority:'normal',rawShellfish:Boolean(body.defaults?.rawShellfish)};return{location,participants,defaults}}

export function createFoodRouter({env=process.env,fetchImpl=globalThis.fetch,storage=createProblemSpaceStorage({env,fetchImpl})}={}){
 const router=express.Router(),googleKey=env.GOOGLE_PLACES_API_KEY;
 router.get('/autocomplete',route(async(req,res)=>{const input=clean(req.query.q);if(input.length<2)return res.json({suggestions:[]});if(!googleKey)return res.json({suggestions:[],provider:'unconfigured'});res.json({suggestions:await googleAutocomplete(fetchImpl,input,googleKey,clean(req.query.sessionToken,100)),provider:'google'})}));
 router.get('/place/:id',route(async(req,res)=>{if(!googleKey)throw Object.assign(new Error('Google Places is not configured.'),{status:503});const place=await googlePlaceLocation(fetchImpl,req.params.id,googleKey);res.json({place:{id:place.id,name:place.displayName?.text,address:place.formattedAddress,location:place.location,types:place.types||[]}})}));
 router.get('/reverse',route(async(req,res)=>{const latitude=number(req.query.latitude),longitude=number(req.query.longitude);if(latitude==null||longitude==null)throw Object.assign(new Error('Latitude and longitude are required.'),{status:400});res.json({location:await reverseLocation(fetchImpl,latitude,longitude)})}));
 router.get('/profile',route(async(req,res)=>{const{value}=await storage.readUser(req,FOOD_SPACE,{defaults:DEFAULT_PROFILE});res.json({profile:{...DEFAULT_PROFILE,...value}})}));
 router.put('/profile',route(async(req,res)=>{const profile=sanitizeProfile(req.body||{}),saved=await storage.writeUser(req,FOOD_SPACE,current=>({...DEFAULT_PROFILE,...current,...profile,decisions:Array.isArray(current.decisions)?current.decisions.slice(0,30):[]}));res.json({profile:saved.value})}));
 router.post('/decisions',route(async(req,res)=>{const decision={id:crypto.randomUUID(),createdAt:new Date().toISOString(),location:req.body?.location||null,request:req.body?.request||null,winner:req.body?.winner||null,alternatives:Array.isArray(req.body?.alternatives)?req.body.alternatives.slice(0,4):[]},saved=await storage.writeUser(req,FOOD_SPACE,current=>({...DEFAULT_PROFILE,...current,decisions:[decision,...(current.decisions||[])].slice(0,30)}));res.status(201).json({decision,decisionCount:saved.value.decisions.length})}));
 router.post('/solve',route(async(req,res)=>{const body=req.body||{},location=body.location||{},latitude=number(location.latitude),longitude=number(location.longitude);if(latitude==null||longitude==null)throw Object.assign(new Error('Confirm a location on the map before solving the food decision.'),{status:400});const center={latitude,longitude},query=queryFrom(body),maxDistanceKm=Math.max(1,Math.min(80,number(body.maxDistanceKm,10))),openNow=Boolean(body.openNow);let places,provider,attribution;
  if(googleKey){const variants=[query];if((body.participants||[]).length>1)variants.push(`good for groups ${query}`);if(body.occasion&&body.occasion!=='meal')variants.push(`${clean(body.occasion,60)} ${query}`);const batches=await Promise.all([...new Set(variants)].slice(0,3).map(value=>googleSearch(fetchImpl,{query:value,center,openNow,maxResults:20,radiusMeters:maxDistanceKm*1000,key:googleKey}).catch(()=>[]))),unique=new Map();for(const place of batches.flat())unique.set(place.id,place);places=[...unique.values()].map(place=>mapGooglePlace(place,center));provider='google';attribution=['Google Places']}
  else{places=await fallbackAround(fetchImpl,{center,query,radius:maxDistanceKm*1000});provider='openstreetmap';attribution=['© OpenStreetMap contributors']}
  const routed=await applyRoadDistances(fetchImpl,center,places);places=routed.places;const solved=solveFoodDecision(places,{...body,query,maxDistanceKm,openNow});res.json({location:{...location,latitude,longitude},provider,attribution,travelDistanceProvider:routed.provider,generatedAt:new Date().toISOString(),...solved})
 }));
 router.get('/search',route(async(req,res)=>{const location={name:clean(req.query.location||'Selected location'),latitude:number(req.query.latitude),longitude:number(req.query.longitude),placeId:clean(req.query.placeId,220)||null};if((location.latitude==null||location.longitude==null)&&location.placeId&&googleKey){const place=await googlePlaceLocation(fetchImpl,location.placeId,googleKey);location.latitude=place.location?.latitude;location.longitude=place.location?.longitude;location.name=place.displayName?.text||location.name;location.address=place.formattedAddress}if(location.latitude==null||location.longitude==null)throw Object.assign(new Error('Choose a specific location or use the map.'),{status:400});req.body={location,query:clean(req.query.q||'restaurant'),openNow:String(req.query.openNow)==='true',maxDistanceKm:number(req.query.maxDistanceKm,10),maxPrice:req.query.maxPrice===''?null:number(req.query.maxPrice),participants:[{name:'You'}],freshnessPriority:'normal'};const center={latitude:location.latitude,longitude:location.longitude},query=req.body.query;let places,provider,attribution;if(googleKey){places=(await googleSearch(fetchImpl,{query,center,openNow:req.body.openNow,maxResults:20,radiusMeters:req.body.maxDistanceKm*1000,key:googleKey})).map(place=>mapGooglePlace(place,center));provider='google';attribution=['Google Places']}else{places=await fallbackAround(fetchImpl,{center,query,radius:req.body.maxDistanceKm*1000});provider='openstreetmap';attribution=['© OpenStreetMap contributors']}const routed=await applyRoadDistances(fetchImpl,center,places);places=routed.places;const solved=solveFoodDecision(places,req.body);res.json({location,provider,attribution,travelDistanceProvider:routed.provider,scoring:solved.method.objective,...solved})}));
 return router;
}
