import express from 'express';

const GALLON_LITERS=3.785411784;
const GBP_USD_SCENARIO=1.33;

const FALLBACKS={
 'United States':{dieselUsdPerLiter:5.348/GALLON_LITERS,weekAgoUsdPerLiter:5.313/GALLON_LITERS,localValue:5.348,localWeekAgo:5.313,localUnit:'USD/gal',sourceDate:'2026-08-03',source:'U.S. EIA Gasoline and Diesel Fuel Update',quality:'official-fallback'},
 'United Kingdom':{dieselUsdPerLiter:1.7919*GBP_USD_SCENARIO,weekAgoUsdPerLiter:1.7397*GBP_USD_SCENARIO,localValue:179.19,localWeekAgo:173.97,localUnit:'pence/litre',sourceDate:'2026-08-03',source:'UK DESNZ Weekly road fuel prices',quality:'official-fallback'},
 'Netherlands':{dieselUsdPerLiter:2.15,weekAgoUsdPerLiter:2.10,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-07-23',source:'EC Weekly Oil Bulletin reference window',quality:'scenario-baseline'},
 'China':{dieselUsdPerLiter:1.08,weekAgoUsdPerLiter:1.06,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'South Korea':{dieselUsdPerLiter:1.23,weekAgoUsdPerLiter:1.20,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'Japan':{dieselUsdPerLiter:1.12,weekAgoUsdPerLiter:1.10,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'Australia':{dieselUsdPerLiter:1.18,weekAgoUsdPerLiter:1.15,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'United Arab Emirates':{dieselUsdPerLiter:.78,weekAgoUsdPerLiter:.76,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'India':{dieselUsdPerLiter:1.08,weekAgoUsdPerLiter:1.08,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'Kenya':{dieselUsdPerLiter:1.29,weekAgoUsdPerLiter:1.26,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'Indonesia':{dieselUsdPerLiter:.72,weekAgoUsdPerLiter:.70,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'},
 'Colombia':{dieselUsdPerLiter:1.02,weekAgoUsdPerLiter:1.00,localValue:null,localWeekAgo:null,localUnit:'scenario USD/litre',sourceDate:'2026-08-03',source:'Atlas Harbor regional baseline',quality:'scenario-baseline'}
};

const round=(value,digits=4)=>Number(Number(value||0).toFixed(digits));
function normalize(country,row){const current=Number(row.dieselUsdPerLiter||0),previous=Number(row.weekAgoUsdPerLiter||current),delta=current-previous;return{country,dieselUsdPerLiter:round(current),weekAgoUsdPerLiter:round(previous),weeklyDeltaUsdPerLiter:round(delta),weeklyDeltaPct:previous?round(delta/previous*100,2):0,localValue:row.localValue,localWeekAgo:row.localWeekAgo,localUnit:row.localUnit,sourceDate:row.sourceDate,source:row.source,quality:row.quality}}

async function eiaApi(fetchImpl,key){if(!key)return null;const url=new URL('https://api.eia.gov/v2/petroleum/pri/gnd/data/');url.searchParams.set('api_key',key);url.searchParams.set('frequency','weekly');url.searchParams.set('data[0]','value');url.searchParams.append('facets[series][]','EMD_EPD2D_PTE_NUS_DPG');url.searchParams.set('sort[0][column]','period');url.searchParams.set('sort[0][direction]','desc');url.searchParams.set('length','2');const response=await fetchImpl(url,{headers:{Accept:'application/json','User-Agent':'AtlasHarbor/1.0'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`EIA API ${response.status}`);const rows=(await response.json())?.response?.data||[];if(rows.length<1)throw new Error('EIA API returned no diesel rows.');const current=Number(rows[0].value),previous=Number(rows[1]?.value||current);if(!Number.isFinite(current))throw new Error('EIA diesel value invalid.');return normalize('United States',{dieselUsdPerLiter:current/GALLON_LITERS,weekAgoUsdPerLiter:previous/GALLON_LITERS,localValue:current,localWeekAgo:previous,localUnit:'USD/gal',sourceDate:rows[0].period,source:'U.S. EIA Open Data API',quality:'official-live'})}

function csvLines(text){return String(text||'').trim().split(/\r?\n/).filter(Boolean)}
async function ukOfficial(fetchImpl){const landing=await fetchImpl('https://www.gov.uk/government/statistics/weekly-road-fuel-prices',{headers:{Accept:'text/html','User-Agent':'AtlasHarbor/1.0'},signal:AbortSignal.timeout(9000)});if(!landing.ok)throw new Error(`GOV.UK ${landing.status}`);const html=await landing.text(),match=html.match(/https:\/\/assets\.publishing\.service\.gov\.uk\/[^"']+weekly_road_fuel_prices_[^"']+\.csv/i)||html.match(/href="([^"]+weekly_road_fuel_prices_[^"]+\.csv)"/i);const href=Array.isArray(match)?(match[1]||match[0]):null;if(!href)throw new Error('Latest UK fuel CSV link not found.');const response=await fetchImpl(href,{headers:{Accept:'text/csv','User-Agent':'AtlasHarbor/1.0'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`UK fuel CSV ${response.status}`);const rows=csvLines(await response.text()).slice(1).map(line=>line.replace(/^\uFEFF/,'').split(',').map(cell=>cell.replace(/^"|"$/g,'').trim())).filter(row=>row.length>=3&&/^\d{2}\/\d{2}\/\d{4}$/.test(row[0]));if(rows.length<1)throw new Error('UK fuel CSV had no price rows.');const current=rows.at(-1),previous=rows.at(-2)||current,pence=Number(current[2]),prior=Number(previous[2]);if(!Number.isFinite(pence))throw new Error('UK diesel value invalid.');const [day,month,year]=current[0].split('/');return normalize('United Kingdom',{dieselUsdPerLiter:pence/100*GBP_USD_SCENARIO,weekAgoUsdPerLiter:prior/100*GBP_USD_SCENARIO,localValue:pence,localWeekAgo:prior,localUnit:'pence/litre',sourceDate:`${year}-${month}-${day}`,source:'UK DESNZ Weekly road fuel prices CSV',quality:'official-live'})}

export async function fuelPrices({fetchImpl=globalThis.fetch,env=process.env}={}){const prices=Object.fromEntries(Object.entries(FALLBACKS).map(([country,row])=>[country,normalize(country,row)]));let usError=null,ukError=null;try{const live=await eiaApi(fetchImpl,env.EIA_API_KEY);if(live)prices['United States']=live}catch(error){usError=error.message}try{prices['United Kingdom']=await ukOfficial(fetchImpl)}catch(error){ukError=error.message}return{prices,meta:{generatedAt:new Date().toISOString(),eiaApiConfigured:Boolean(env.EIA_API_KEY),usError,ukError,notes:['U.S. EIA API is free but requires a registered API key.','UK DESNZ publishes a public weekly CSV.','EC Weekly Oil Bulletin is the official EU reference; non-live country rows remain explicit gameplay baselines until a machine-readable adapter is configured.','Scenario USD conversions are game inputs, not fuel quotations.']}}}

export function createGameFuelRouter({fetchImpl=globalThis.fetch,env=process.env}={}){const router=express.Router();router.get('/api/game/fuel-prices',async(_req,res)=>{try{const data=await fuelPrices({fetchImpl,env});res.set('Cache-Control','public,max-age=1800,stale-while-revalidate=21600');return res.json(data)}catch(error){return res.status(502).json({error:error.message})}});return router}
