import fs from'node:fs/promises';
import path from'node:path';
import crypto from'node:crypto';
import{fileURLToPath}from'node:url';
import{createProblemSpaceStorage}from'./problem-space-storage.js';
import{createCourtListenerClient,extractCourtListenerHints}from'./courtlistener.js';

const directory=path.dirname(fileURLToPath(import.meta.url));
const caseDirectory=path.join(directory,'../data/legal/cases');
const proposalDirectory=path.join(directory,'../data/legal/proposals');
const LEGAL_SPACE='legal_tracker';
const FIVE_MINUTES=5*60*1000;
const DEFAULT_STORE={cases:[],syncRuns:[],initializedAt:null,updatedAt:null};
const readJson=file=>fs.readFile(file,'utf8').then(JSON.parse);
const text=value=>String(value??'').trim();
const slugOk=slug=>/^[a-z0-9-]+$/.test(slug);
const now=()=>new Date().toISOString();
const dbConfig=env=>env.SUPABASE_URL&&env.SUPABASE_SECRET_KEY?{url:env.SUPABASE_URL.replace(/\/$/,''),key:env.SUPABASE_SECRET_KEY}:null;

async function fileCases(){const names=(await fs.readdir(caseDirectory)).filter(name=>name.endsWith('.json'));return Promise.all(names.map(name=>readJson(path.join(caseDirectory,name))))}
function uniqueBy(items,key){const seen=new Set();return(items||[]).filter(item=>{const value=key(item);if(!value||seen.has(value))return false;seen.add(value);return true})}
function cleanDate(value){return /^\d{4}-\d{2}-\d{2}/.test(text(value))?text(value).slice(0,10):text(value)||null}
function sourceUrl(value){try{return new URL(value).toString()}catch{return null}}
function compact(record){const{timeline=[],positions,docketEntries=[],documents=[],parties=[],researchRuns=[],...item}=record;return{...item,timelineCount:timeline.length,docketEntryCount:docketEntries.length,documentCount:documents.length,partyCount:parties.length,researchRunCount:researchRuns.length,latestFilingAt:record.courtListener?.dateLastFiling||docketEntries[0]?.dateFiled||null}}

function normalizedSource(source){const url=sourceUrl(source?.url);if(!url)return null;return{title:text(source.title)||'Source',url,type:source.type||source.sourceType||'primary',verifiedAt:source.verifiedAt||source.publishedAt||null,supports:source.supports||null}}
function normalizeCase(input){
 const record=structuredClone(input||{}),hints=extractCourtListenerHints(record),sources=(record.sources||[]).map(normalizedSource).filter(Boolean);
 if(hints.seedDocumentUrl&&!sources.some(source=>source.url===hints.seedDocumentUrl))sources.unshift({title:'Complaint · RECAP document 1',url:hints.seedDocumentUrl,type:'primary',verifiedAt:'2026-06-08',supports:'Initial complaint and pleaded allegations.'});
 if(hints.docketId&&!sources.some(source=>/courtlistener\.com\/docket\//i.test(source.url)))sources.unshift({title:'CourtListener docket',url:`https://www.courtlistener.com/docket/${hints.docketId}/`,type:'primary',verifiedAt:null,supports:'Structured docket metadata and filings.'});
 return{...record,slug:text(record.slug),title:text(record.title||record.shortTitle)||'Untitled matter',shortTitle:text(record.shortTitle||record.title)||'Untitled matter',sources,courtListener:{...(record.courtListener||{}),...hints},timeline:Array.isArray(record.timeline)?record.timeline:[],documents:Array.isArray(record.documents)?record.documents:[],docketEntries:Array.isArray(record.docketEntries)?record.docketEntries:[],parties:Array.isArray(record.parties)?record.parties:[],researchRuns:Array.isArray(record.researchRuns)?record.researchRuns:[]};
}

function classifyDocument(document){const value=text(document.description).toLowerCase();if(/order|opinion|judgment|memorandum decision/.test(value))return'Order';if(/complaint|petition/.test(value))return'Pleading';if(/motion/.test(value))return'Motion';if(/memorandum|brief|response|reply/.test(value))return'Briefing';if(/exhibit|attachment/.test(value))return'Exhibit';if(/notice|summons|waiver/.test(value))return'Notice';return'Filing'}
function documentScore(document,question=''){const value=`${document.description} ${document.dateFiled}`.toLowerCase(),terms=text(question).toLowerCase().split(/[^a-z0-9]+/).filter(term=>term.length>3);let score={Order:90,Pleading:84,Motion:74,Briefing:68,Exhibit:25,Notice:20,Filing:35}[classifyDocument(document)]||20;if(document.isAvailable)score+=15;if(document.dateFiled)score+=Math.max(0,20-Math.floor((Date.now()-Date.parse(document.dateFiled))/(30*86400000)));for(const term of terms)if(value.includes(term))score+=18;return score}
function inferStage(entries,record){const value=entries.slice(0,20).map(item=>item.description).join(' ').toLowerCase();if(/judgment|case dismissed|terminated|settlement/.test(value))return'Post-decision or closed';if(/trial|pretrial order|jury instructions/.test(value))return'Trial preparation';if(/summary judgment/.test(value))return'Summary-judgment briefing';if(/discovery|deposition|interrogator|subpoena/.test(value))return'Discovery';if(/preliminary injunction|temporary restraining|motion to dismiss|answer filed/.test(value))return'Motions practice';return record.proceduralStage||'Early case development'}
function buildDecisionBoard(record,entries,documents){
 const latest=entries.slice(0,8),important=[...documents].sort((a,b)=>documentScore(b)-documentScore(a)).slice(0,6),stage=inferStage(entries,record),latestDescription=latest[0]?.description||'No docket entry has been synchronized yet.';
 const activeMotions=latest.filter(item=>/motion|application|request/i.test(item.description)).slice(0,4);
 return{
  stage,
  currentPosition:`The newest synchronized filing is ${latest[0]?.dateFiled||'undated'}: ${latestDescription}`,
  actionQueue:[
   important[0]?`Read ${important[0].description} before forming a view.`:'Confirm the primary pleading and latest operative order.',
   activeMotions[0]?`Identify the requested relief and response posture for: ${activeMotions[0].description}`:'Determine which requests are presently pending.',
   'Calendar deadlines only from the operative docket entry or order; do not infer them from a summary.',
   'Separate pleaded allegations, evidence, procedural rulings, and final holdings in every analysis.'
  ],
  openQuestions:[
   'What legal standard controls the next contested decision?',
   'Which facts are admitted, disputed, or supported only by allegations?',
   'What filing or evidence would materially change the recommended next step?',
   'Which deadline, hearing, or response is the next operational constraint?'
  ],
  latestDevelopments:latest.map(item=>({date:item.dateFiled,entryNumber:item.entryNumber,description:item.description,url:item.courtListenerUrl||item.documents?.[0]?.pdfUrl||null})),
  documentsToRead:important.map(item=>({id:item.id,date:item.dateFiled,description:item.description,category:classifyDocument(item),pdfUrl:item.pdfUrl,courtListenerUrl:item.courtListenerUrl}))
 };
}
function mergeTimeline(existing,entries){const additions=entries.slice(0,80).map(item=>({date:item.dateFiled||'Undated',event:item.description,sourceUrl:item.courtListenerUrl||item.documents?.[0]?.pdfUrl||null,source:'CourtListener/RECAP'}));return uniqueBy([...(existing||[]),...additions],item=>`${item.date}|${item.event}`).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-180)}
function mergeSources(existing,bundle){const additions=[{title:'CourtListener docket',url:bundle.docket.courtListenerUrl,type:'primary',verifiedAt:bundle.fetchedAt,supports:'Docket metadata, filing dates, and document availability.'},...bundle.documents.filter(item=>item.pdfUrl).slice(0,80).map(item=>({title:`${item.dateFiled||'Undated'} · ${item.description}`,url:item.pdfUrl,type:'primary',verifiedAt:bundle.fetchedAt,supports:'Filed document in the RECAP archive.'}))];return uniqueBy([...(existing||[]).map(normalizedSource).filter(Boolean),...additions],item=>item.url).slice(0,140)}

async function dbRequest(fetchImpl,config,table,query='',options={}){const response=await fetchImpl(`${config.url}/rest/v1/${table}${query}`,{...options,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,'Content-Type':'application/json',Prefer:options.method==='POST'?'return=representation,resolution=merge-duplicates':'return=representation',...(options.headers||{})}}),body=await response.text();if(!response.ok){const error=new Error(`${table} ${response.status}: ${body}`);error.status=response.status;throw error}if(response.status===204||!body)return null;return JSON.parse(body)}
function outputText(data){return text(data?.choices?.[0]?.message?.content||data?.output_text||data?.output?.flatMap(item=>item?.content||[]).map(item=>item?.text||item?.content||'').filter(Boolean).join('\n'))}
function outputCitations(data){const raw=data?.citations||data?.search_results||data?.choices?.[0]?.message?.citations||data?.choices?.[0]?.message?.annotations||[];return(Array.isArray(raw)?raw:[]).map(item=>typeof item==='string'?{url:item}:{title:item.title||item.name||'',url:item.url||item.uri||item.source?.url||'',snippet:item.snippet||item.text||''}).filter(item=>item.url)}

export function createLegalService({fetchImpl=globalThis.fetch,env=process.env}={}){
 const db=dbConfig(env),storage=createProblemSpaceStorage({env,fetchImpl}),courtListener=createCourtListenerClient({env,fetchImpl});
 let tableAvailable=db?null:false,seedPromise=null,scheduler=null;
 const syncCache=new Map(),analysisCache=new Map();
 async function tableRecords(){if(!db||tableAvailable===false)return null;try{const rows=await dbRequest(fetchImpl,db,'legal_cases','?select=record&order=filed_at.desc.nullslast');tableAvailable=true;return(rows||[]).map(row=>normalizeCase(row.record))}catch(error){tableAvailable=false;console.warn('legal_cases is unavailable; using application-managed Supabase metadata.',error.message);return null}}
 async function metadataRecords(){if(!storage.configured)return null;try{const value=await storage.readGlobal(LEGAL_SPACE,{defaults:DEFAULT_STORE});return(value.cases||[]).map(normalizeCase)}catch(error){console.warn('Legal metadata store unavailable.',error.message);return null}}
 async function persistMetadata(records,extra={}){if(!storage.configured)return false;try{await storage.writeGlobal(LEGAL_SPACE,current=>({...DEFAULT_STORE,...current,...extra,cases:records.map(normalizeCase),updatedAt:now(),initializedAt:current.initializedAt||now()}));return true}catch(error){console.warn('Could not persist Legal metadata.',error.message);return false}}
 async function persistTable(record){if(!db||tableAvailable===false)return false;try{await dbRequest(fetchImpl,db,'legal_cases','?on_conflict=slug',{method:'POST',body:JSON.stringify({slug:record.slug,record,filed_at:record.filedAt||null,updated_at:now()})});tableAvailable=true;return true}catch(error){tableAvailable=false;console.warn('Could not persist Legal case table; using metadata.',error.message);return false}}
 async function existingRecords(){const rows=await tableRecords();if(rows?.length)return{records:rows,mode:'legal_cases'};const metadata=await metadataRecords();if(metadata?.length)return{records:metadata,mode:'supabase-account-metadata'};return{records:[],mode:tableAvailable?'legal_cases':'repository-seeds'}}
 async function seed({force=false}={}){if(seedPromise)return seedPromise;seedPromise=(async()=>{const existing=await existingRecords();if(existing.records.length&&!force)return{seeded:0,total:existing.records.length,storage:existing.mode,alreadyInitialized:true};const seeds=(await fileCases()).map(normalizeCase);let mode='repository-seeds';if(tableAvailable!==false&&db){const results=await Promise.all(seeds.map(persistTable));if(results.some(Boolean))mode='legal_cases'}if(mode!=='legal_cases'&&await persistMetadata(seeds,{seededAt:now()}))mode='supabase-account-metadata';return{seeded:seeds.length,total:seeds.length,storage:mode,alreadyInitialized:false}})().finally(()=>{seedPromise=null});return seedPromise}
 async function allRecords(){let existing=await existingRecords();if(!existing.records.length){await seed();existing=await existingRecords()}if(existing.records.length)return existing.records;return(await fileCases()).map(normalizeCase)}
 async function saveCase(record){const normalized=normalizeCase({...record,updatedAt:now()});if(await persistTable(normalized))return normalized;const records=await allRecords(),next=[normalized,...records.filter(item=>item.slug!==normalized.slug)];await persistMetadata(next);return normalized}
 async function getCase(slug){if(!slugOk(slug))return null;const record=(await allRecords()).find(item=>item.slug===slug);if(!record)return null;let latestProposal=null;try{latestProposal=await readJson(path.join(proposalDirectory,`${slug}.json`))}catch{}return{...record,latestProposal}}
 async function listCases(){return(await allRecords()).map(compact).sort((a,b)=>String(b.filedAt).localeCompare(String(a.filedAt)))}
 async function refreshFromCourtListener(slug,{force=false,trigger='manual'}={}){
  const cached=syncCache.get(slug);if(!force&&cached&&Date.now()-cached.at<FIVE_MINUTES)return{...cached.value,cached:true};
  const record=await getCase(slug);if(!record)return null;const bundle=await courtListener.docketBundle(record);if(!bundle)throw Object.assign(new Error('CourtListener could not resolve this case. Add or verify its docket number, court code, PACER case ID, or CourtListener URL.'),{status:404});
  const courtListenerData={...(record.courtListener||{}),...bundle.docket,lastSyncedAt:bundle.fetchedAt,tokenConfigured:bundle.tokenConfigured};
  const documents=bundle.documents.map(item=>({...item,category:classifyDocument(item)})).slice(0,140),docketEntries=bundle.entries.slice(0,180);
  const updated=await saveCase({...record,title:bundle.docket.caseName||record.title,indexNumber:bundle.docket.docketNumber||record.indexNumber,filedAt:bundle.docket.dateFiled||record.filedAt,status:bundle.docket.dateTerminated?'Closed':record.status||'Active',courtListener:courtListenerData,lastVerifiedAt:bundle.fetchedAt,docketEntries,documents,parties:bundle.parties,timeline:mergeTimeline(record.timeline,docketEntries),sources:mergeSources(record.sources,bundle),proceduralStage:inferStage(docketEntries,record),decisionBoard:buildDecisionBoard(record,docketEntries,documents),dataQuality:{...(record.dataQuality||{}),courtListener:`Synchronized ${bundle.fetchedAt}`,documentCoverage:`${documents.filter(item=>item.isAvailable).length} available RECAP documents of ${documents.length} indexed documents`}});
  const value={ok:true,slug,trigger,record:updated,docketId:bundle.docket.id,entries:docketEntries.length,documents:documents.length,availableDocuments:documents.filter(item=>item.isAvailable).length,syncedAt:bundle.fetchedAt,cached:false};syncCache.set(slug,{at:Date.now(),value});
  try{const store=await storage.readGlobal(LEGAL_SPACE,{defaults:DEFAULT_STORE});await storage.writeGlobal(LEGAL_SPACE,current=>({...DEFAULT_STORE,...current,syncRuns:[{id:crypto.randomUUID(),slug,trigger,ranAt:bundle.fetchedAt,entries:value.entries,documents:value.documents},...(current.syncRuns||[])].slice(0,80)}))}catch{}
  return value;
 }
 async function refreshAll({force=false,trigger='admin',limit=100}={}){const cases=(await listCases()).slice(0,limit),results=[];for(const item of cases){try{results.push(await refreshFromCourtListener(item.slug,{force,trigger}))}catch(error){results.push({ok:false,slug:item.slug,error:error.message})}}return{ok:true,ranAt:now(),total:cases.length,updated:results.filter(item=>item?.ok).length,failed:results.filter(item=>!item?.ok).length,results}}
 async function status(){const existing=await existingRecords(),cases=existing.records;return{configured:storage.configured||Boolean(db),storage:cases.length?existing.mode:tableAvailable?'legal_cases':'repository-seeds',caseCount:cases.length,courtListenerTokenConfigured:courtListener.tokenConfigured,lastSyncedAt:cases.map(item=>item.courtListener?.lastSyncedAt).filter(Boolean).sort().at(-1)||null,documentCount:cases.reduce((sum,item)=>sum+(item.documents?.length||0),0)}}
 async function analysisContext(slug,{question='',documentIds=[]}={}){const record=await getCase(slug);if(!record)return null;const requested=new Set((documentIds||[]).map(String)),ranked=[...(record.documents||[])].sort((a,b)=>documentScore(b,question)-documentScore(a,question)),chosen=(requested.size?ranked.filter(item=>requested.has(String(item.id))):ranked).slice(0,5),documents=[];for(const item of chosen){let plainText='';if(item.courtListenerId){try{plainText=(await courtListener.document(item.courtListenerId,{includeText:true})).plainText||''}catch{}}documents.push({...item,plainText:plainText.slice(0,50000)})}return{case:{slug:record.slug,title:record.title,court:record.court,indexNumber:record.indexNumber,status:record.status,proceduralStage:record.proceduralStage,summary:record.summary,coreQuestion:record.coreQuestion,courtListener:record.courtListener,decisionBoard:record.decisionBoard,positions:record.positions,nextWatchItems:record.nextWatchItems,dataQuality:record.dataQuality},question,selectedDocuments:documents.map(item=>({id:item.id,dateFiled:item.dateFiled,description:item.description,pdfUrl:item.pdfUrl,category:item.category,text:item.plainText})),instruction:'Use only this synchronized case record and the selected filing text for case-specific factual claims. Clearly distinguish allegations, evidence, procedural orders, holdings, and inference. Cite filings by description and URL.'}}
 async function askPerplexity(slug,{question,documentIds=[],apiKey,model='sonar-pro'}={}){if(!apiKey)throw Object.assign(new Error('A Perplexity API key is required.'),{status:400});const key=crypto.createHash('sha256').update(`${slug}|${question}|${documentIds.join(',')}|${model}`).digest('hex'),cached=analysisCache.get(key);if(cached&&Date.now()-cached.at<FIVE_MINUTES)return{...cached.value,cached:true};const context=await analysisContext(slug,{question,documentIds});if(!context)throw Object.assign(new Error('Case not found.'),{status:404});const response=await fetchImpl('https://api.perplexity.ai/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:'You are a cautious legal research assistant. Answer the user’s operational question using the supplied court record. Separate allegations, evidence, procedural events, and holdings. Cite the selected documents and any current web sources. Do not provide legal advice or fabricate deadlines.'},{role:'user',content:`Question:\n${question}\n\nSynchronized case context:\n${JSON.stringify(context)}`}],temperature:.1}),signal:AbortSignal.timeout(120000)}),body=await response.text();let data={};try{data=JSON.parse(body)}catch{}if(!response.ok)throw Object.assign(new Error(data?.error?.message||data?.message||body||`Perplexity returned ${response.status}.`),{status:response.status});const value={ok:true,model:data.model||model,answer:outputText(data),citations:outputCitations(data),selectedDocuments:context.selectedDocuments.map(item=>({id:item.id,description:item.description,pdfUrl:item.pdfUrl})),cached:false};analysisCache.set(key,{at:Date.now(),value});return value}
 async function saveResearchRun(slug,run){const record=await getCase(slug);if(!record)return null;return saveCase({...record,researchRuns:[run,...(record.researchRuns||[])].slice(0,30)})}
 async function document(slug,id){const record=await getCase(slug);if(!record)return null;const item=(record.documents||[]).find(document=>String(document.id)===String(id));if(!item)return null;if(item.courtListenerId){try{return{...item,...await courtListener.document(item.courtListenerId,{includeText:true})}}catch{}}return item}
 async function authUser(req){return storage.requestUser(req)}
 function startScheduler(){if(scheduler||!courtListener.tokenConfigured)return;scheduler=setInterval(async()=>{try{const cases=await allRecords(),cutoff=Date.now()-12*3600000,stale=cases.filter(item=>!item.courtListener?.lastSyncedAt||Date.parse(item.courtListener.lastSyncedAt)<cutoff).slice(0,4);for(const item of stale)await refreshFromCourtListener(item.slug,{trigger:'scheduled'}).catch(error=>console.warn(`Legal sync ${item.slug}:`,error.message))}catch(error){console.warn('Legal scheduler:',error.message)}},15*60*1000);scheduler.unref?.();setTimeout(()=>{const timer=setTimeout(()=>{},0);clearTimeout(timer);(async()=>{try{const cases=await allRecords(),stale=cases.filter(item=>!item.courtListener?.lastSyncedAt).slice(0,4);for(const item of stale)await refreshFromCourtListener(item.slug,{trigger:'startup'}).catch(error=>console.warn(`Legal startup sync ${item.slug}:`,error.message))}catch(error){console.warn('Legal startup sync:',error.message)}})()},20000).unref?.()}
 return{listCases,getCase,saveCase,seed,status,refreshFromCourtListener,refreshAll,refreshCase:refreshFromCourtListener,analysisContext,askPerplexity,saveResearchRun,document,authUser,startScheduler,courtListenerTokenConfigured:courtListener.tokenConfigured};
}
