import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const directory = path.dirname(fileURLToPath(import.meta.url));
const caseDirectory = path.join(directory, "../data/legal/cases");
const proposalDirectory = path.join(directory, "../data/legal/proposals");
const defaultDiscoveryDomains=["courtlistener.com","law.justia.com","docs.justia.com","dockets.justia.com","catribunal.org.uk","bailii.org","uscourts.gov","justice.gov","epa.gov","eeoc.gov","ftc.gov","cftc.gov"];

const updateSchema={name:"legal_case_update",strict:true,schema:{type:"object",additionalProperties:false,required:["caseSlug","checkedAt","summary","changes","noMaterialChange","sources","confidence","warnings"],properties:{caseSlug:{type:"string"},checkedAt:{type:"string"},summary:{type:"string"},noMaterialChange:{type:"boolean"},confidence:{type:"string",enum:["low","medium","high"]},warnings:{type:"array",items:{type:"string"}},changes:{type:"array",items:{type:"object",additionalProperties:false,required:["field","oldValue","newValue","reason","sourceUrls"],properties:{field:{type:"string"},oldValue:{},newValue:{},reason:{type:"string"},sourceUrls:{type:"array",items:{type:"string"}}}}},sources:{type:"array",items:{type:"object",additionalProperties:false,required:["title","url","sourceType","publishedAt","supports"],properties:{title:{type:"string"},url:{type:"string"},sourceType:{type:"string",enum:["primary","secondary"]},publishedAt:{type:["string","null"]},supports:{type:"string"}}}}}}};
async function readJson(file){return JSON.parse(await fs.readFile(file,"utf8"))}

export function createLegalService({fetchImpl=globalThis.fetch,env=process.env}={}){
 return{
  async listCases(){const names=(await fs.readdir(caseDirectory)).filter(n=>n.endsWith(".json"));const cases=await Promise.all(names.map(n=>readJson(path.join(caseDirectory,n))));return cases.map(({timeline=[],positions,...item})=>({...item,timelineCount:timeline.length})).sort((a,b)=>String(b.filedAt).localeCompare(String(a.filedAt)))},
  async getCase(slug){if(!/^[a-z0-9-]+$/.test(slug))return null;try{const record=await readJson(path.join(caseDirectory,`${slug}.json`));let latestProposal=null;try{latestProposal=await readJson(path.join(proposalDirectory,`${slug}.json`))}catch{}return{...record,latestProposal}}catch(error){if(error.code==="ENOENT")return null;throw error}},
  async refreshCase(slug){if(!env.OPENROUTER_API_KEY)throw new Error("OPENROUTER_API_KEY is not configured");const record=await this.getCase(slug);if(!record)return null;const recordDomains=(record.sources||[]).flatMap(source=>{try{return[new URL(source.url).hostname]}catch{return[]}});const sourceDomains=[...new Set([...recordDomains,...defaultDiscoveryDomains])];const prompt=["You are updating a structured legal case tracker. Research only verifiable developments after lastVerifiedAt.","Start with primary court, tribunal, agency, and legislative sources. CourtListener/RECAP, Justia dockets, BAILII, and official tribunal search may be used as discovery indexes, but distinguish docket metadata from holdings.","Preserve jurisdictionTags, lawTopics, and keywords. Propose changes when a new order, filing, consolidation, certification event, deadline, party, docket identifier, or source is verified.","Never convert contextual reporting into a pleaded claim. Preserve data-quality flags such as allegationStatus=unproven, collectiveActionCertified=false, botClickClaim=false, or drinkingWaterClaim=false unless a primary filing supports a change.","Do not provide legal advice or state predictions as facts. Distinguish allegations, preliminary rulings, final holdings, and procedural events.",`Current UTC time: ${new Date().toISOString()}`,`Canonical record: ${JSON.stringify(record)}`].join("\n\n");const response=await fetchImpl("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${env.OPENROUTER_API_KEY}`,"Content-Type":"application/json","HTTP-Referer":env.PUBLIC_APP_URL??"https://github.com/AtlasHarbor/AtlasHarbor","X-OpenRouter-Title":"Atlas Harbor Legal Tracker"},body:JSON.stringify({model:env.OPENROUTER_LEGAL_MODEL??"openai/gpt-5.2",messages:[{role:"user",content:prompt}],tools:[{type:"openrouter:web_search",parameters:{engine:"auto",max_results:10,max_total_results:24,allowed_domains:sourceDomains}}],response_format:{type:"json_schema",json_schema:updateSchema},provider:{require_parameters:true}}),signal:AbortSignal.timeout(90000)});if(!response.ok)throw new Error(`OpenRouter responded with ${response.status}`);const data=await response.json(),content=data.choices?.[0]?.message?.content;if(!content)throw new Error("OpenRouter returned no update content");const proposal=JSON.parse(content);proposal.model=data.model??env.OPENROUTER_LEGAL_MODEL;proposal.annotations=data.choices?.[0]?.message?.annotations??[];await fs.mkdir(proposalDirectory,{recursive:true});await fs.writeFile(path.join(proposalDirectory,`${slug}.json`),JSON.stringify(proposal,null,2));return proposal}
 }
}
