import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const directory=path.dirname(fileURLToPath(import.meta.url));
const caseDirectory=path.join(directory,"../data/legal/cases");
const proposalDirectory=path.join(directory,"../data/legal/proposals");
const defaultDiscoveryDomains=["courtlistener.com","law.justia.com","docs.justia.com","dockets.justia.com","catribunal.org.uk","bailii.org","uscourts.gov","justice.gov","epa.gov","eeoc.gov","ftc.gov","cftc.gov"];
const updateSchema={name:"legal_case_update",strict:true,schema:{type:"object",additionalProperties:false,required:["caseSlug","checkedAt","summary","changes","noMaterialChange","sources","confidence","warnings"],properties:{caseSlug:{type:"string"},checkedAt:{type:"string"},summary:{type:"string"},noMaterialChange:{type:"boolean"},confidence:{type:"string",enum:["low","medium","high"]},warnings:{type:"array",items:{type:"string"}},changes:{type:"array",items:{type:"object",additionalProperties:false,required:["field","oldValue","newValue","reason","sourceUrls"],properties:{field:{type:"string"},oldValue:{},newValue:{},reason:{type:"string"},sourceUrls:{type:"array",items:{type:"string"}}}}},sources:{type:"array",items:{type:"object",additionalProperties:false,required:["title","url","sourceType","publishedAt","supports"],properties:{title:{type:"string"},url:{type:"string"},sourceType:{type:"string",enum:["primary","secondary"]},publishedAt:{type:["string","null"]},supports:{type:"string"}}}}}}};
const readJson=file=>fs.readFile(file,"utf8").then(JSON.parse);
const dbConfig=env=>env.SUPABASE_URL&&env.SUPABASE_SECRET_KEY?{url:env.SUPABASE_URL.replace(/\/$/,""),key:env.SUPABASE_SECRET_KEY}:null;
async function dbRequest(config,table,query="",options={}){const r=await fetch(`${config.url}/rest/v1/${table}${query}`,{...options,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,'Content-Type':'application/json',Prefer:options.method==='POST'?'return=representation,resolution=merge-duplicates':'return=representation',...(options.headers||{})}});if(!r.ok)throw new Error(`${table} ${r.status}: ${await r.text()}`);if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}
async function fileCases(){const names=(await fs.readdir(caseDirectory)).filter(n=>n.endsWith('.json'));return Promise.all(names.map(n=>readJson(path.join(caseDirectory,n))))}
function compact(c){const{timeline=[],positions,...item}=c;return{...item,timelineCount:timeline.length}}

export function createLegalService({fetchImpl=globalThis.fetch,env=process.env}={}){
 const db=dbConfig(env);
 async function dbList(){if(!db)return null;try{const rows=await dbRequest(db,'legal_cases','?select=record&order=filed_at.desc.nullslast');return rows.map(r=>compact(r.record))}catch(e){console.warn('Legal database unavailable; using repository seed files.',e.message);return null}}
 async function dbGet(slug){if(!db)return null;try{const rows=await dbRequest(db,'legal_cases',`?slug=eq.${encodeURIComponent(slug)}&select=record&limit=1`);return rows?.[0]?.record||null}catch(e){console.warn('Legal database lookup failed; using repository seed file.',e.message);return null}}
 return{
  async listCases(){return await dbList()||(await fileCases()).map(compact).sort((a,b)=>String(b.filedAt).localeCompare(String(a.filedAt)))},
  async getCase(slug){if(!/^[a-z0-9-]+$/.test(slug))return null;let record=await dbGet(slug);if(!record){try{record=await readJson(path.join(caseDirectory,`${slug}.json`))}catch(error){if(error.code==='ENOENT')return null;throw error}}let latestProposal=null;if(db){try{const rows=await dbRequest(db,'legal_case_update_proposals',`?case_slug=eq.${encodeURIComponent(slug)}&select=proposal&order=created_at.desc&limit=1`);latestProposal=rows?.[0]?.proposal||null}catch{}}if(!latestProposal){try{latestProposal=await readJson(path.join(proposalDirectory,`${slug}.json`))}catch{}}return{...record,latestProposal}},
  async refreshCase(slug){if(!env.OPENROUTER_API_KEY)throw new Error('OPENROUTER_API_KEY is not configured');const record=await this.getCase(slug);if(!record)return null;const recordDomains=(record.sources||[]).flatMap(source=>{try{return[new URL(source.url).hostname]}catch{return[]}});const sourceDomains=[...new Set([...recordDomains,...defaultDiscoveryDomains])];const prompt=["You are updating a structured legal case tracker. Research only verifiable developments after lastVerifiedAt.","Start with primary court, tribunal, agency, and legislative sources. CourtListener/RECAP, Justia dockets, BAILII, and official tribunal search may be used as discovery indexes, but distinguish docket metadata from holdings.","Preserve jurisdictionTags, lawTopics, keywords, proceduralStage, allegationStatus, and dataQuality. Propose changes only when a source supports them.","Never convert contextual reporting into a pleaded claim. Preserve flags such as collectiveActionCertified=false, botClickClaim=false, drinkingWaterClaim=false, and personalDefendantElonMusk=false unless a primary filing supports a change.","Do not provide legal advice or state predictions as facts. Distinguish allegations, preliminary rulings, final holdings, and procedural events.",`Current UTC time: ${new Date().toISOString()}`,`Canonical record: ${JSON.stringify(record)}`].join('\n\n');const response=await fetchImpl('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':env.PUBLIC_APP_URL||'https://github.com/AtlasHarbor/AtlasHarbor','X-OpenRouter-Title':'Atlas Harbor Legal Tracker'},body:JSON.stringify({model:env.OPENROUTER_LEGAL_MODEL||'openai/gpt-5.2',messages:[{role:'user',content:prompt}],tools:[{type:'openrouter:web_search',parameters:{engine:'auto',max_results:10,max_total_results:24,allowed_domains:sourceDomains}}],response_format:{type:'json_schema',json_schema:updateSchema},provider:{require_parameters:true}}),signal:AbortSignal.timeout(90000)});if(!response.ok)throw new Error(`OpenRouter responded with ${response.status}`);const data=await response.json(),content=data.choices?.[0]?.message?.content;if(!content)throw new Error('OpenRouter returned no update content');const proposal=JSON.parse(content);proposal.model=data.model||env.OPENROUTER_LEGAL_MODEL;proposal.annotations=data.choices?.[0]?.message?.annotations||[];await fs.mkdir(proposalDirectory,{recursive:true});await fs.writeFile(path.join(proposalDirectory,`${slug}.json`),JSON.stringify(proposal,null,2));if(db){try{await dbRequest(db,'legal_case_update_proposals','',{method:'POST',body:JSON.stringify({case_slug:slug,status:'pending',proposal,model:proposal.model,checked_at:proposal.checkedAt||new Date().toISOString()})})}catch(e){console.warn('Could not persist legal proposal to Supabase.',e.message)}}return proposal}
 }
}
