import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createProblemSpacesService} from './problem-spaces.js';
import {createProblemSpaceStorage} from './problem-space-storage.js';
import {createAdminMetadataControl} from './admin-metadata-control.js';
import {createAdminResearchRouter} from './admin-research.js';
import {createEconomicsService} from './economics-service.js';
import {createEconomicsRouter} from './economics.js';
import {createDropshippingRouter} from './dropshipping-api.js';
import {createWorkspaceRouter} from './workspace-api.js';
import {createPublishedFeedRouter} from './published-feed.js';
import {createBaseballProspectRouter} from './baseball-prospect-router.js';
import {createBaseballSearchRouter} from './baseball-search-router.js';
import {createGameRoutingRouter} from './game-routing.js';
import {createGameFuelRouter} from './game-fuel.js';
import {createGameClientRouter} from './game-client.js';
import {createLegalService} from './legal.js';
import {createLegalRouter} from './legal-router.js';
import {createGoToMarketRouter} from './go-to-market.js';
import {createPropositionRouter} from './proposition.js';
import {createPublicPropositionRouter} from './proposition-public.js';
import {createResearchProjectsRouter} from './research-projects.js';
import {createResearchCredentialRouter} from './research-credentials.js';
import {createLifeSciencesRouter} from './life-sciences.js';

const directory=path.dirname(fileURLToPath(import.meta.url));
export function createProblemRouter({service=createProblemSpacesService(),env=process.env}={}){
 const router=express.Router(),legal=createLegalService({env}),storage=createProblemSpaceStorage({env}),economicsService=createEconomicsService({storage,env});
 economicsService.startScheduler();legal.startScheduler();
 router.get('/runtime-config.js',(_req,res)=>{const configured=Boolean(env.SUPABASE_URL&&env.SUPABASE_PUBLISHABLE_KEY),payload={configured,supabaseUrl:configured?env.SUPABASE_URL:null,supabasePublishableKey:configured?env.SUPABASE_PUBLISHABLE_KEY:null};res.set('Cache-Control','no-store');res.type('application/javascript').send(`window.__ATLAS_CONFIG__=${JSON.stringify(payload)};`)});
 router.use(createGameClientRouter());router.use(createBaseballSearchRouter());router.use(createBaseballProspectRouter({legal}));router.use(createGameRoutingRouter());router.use(createGameFuelRouter({env}));router.use(createLegalRouter({service:legal}));
 router.get(['/economics','/economics/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/economics.html')));
 router.get(['/prop','/prop/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/prop.html')));
 router.get(['/go-to-market','/go-to-market/{*path}'],(req,res)=>res.redirect(301,req.originalUrl.replace(/^\/go-to-market/,'/prop')));
 router.get(['/leads','/leads/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/leads.html')));
 router.get(['/logistics','/logistics/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/logistics-planner.html')));
 router.get(['/life-sciences','/life-sciences/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/life-sciences.html')));
 router.get(['/users/:slug','/users/:slug/{*path}'],(_req,res)=>res.sendFile(path.join(directory,'../public/profile.html')));
 router.use(createEconomicsRouter({service:economicsService,storage}));router.use(createDropshippingRouter({storage}));router.use(createPublicPropositionRouter({storage}));router.use(createPropositionRouter({storage}));router.use(createGoToMarketRouter({storage}));router.use(createResearchCredentialRouter({storage}));router.use(createResearchProjectsRouter({storage}));router.use(createLifeSciencesRouter({storage}));router.use(createWorkspaceRouter({env,storage}));router.use(createAdminMetadataControl({env}));router.use(createAdminResearchRouter({env,legalService:legal}));
 router.get('/api/published-feed',(req,_res,next)=>{delete req.headers.authorization;next()});
 router.use(createPublishedFeedRouter({env}));
 const legacyAdminOk=req=>Boolean(env.ADMIN_PASSWORD)&&req.get('x-admin-password')===env.ADMIN_PASSWORD;
 router.get('/api/problem-spaces',async(_req,res)=>{try{return res.json({spaces:await service.listPublic()})}catch(error){console.error(error);return res.status(500).json({error:'Problem spaces are temporarily unavailable.'})}});
 router.post('/api/problem-spaces/requests',async(req,res)=>{try{return res.status(201).json({request:await service.create(req.body||{})})}catch(error){return res.status(400).json({error:error.message})}});
 router.get('/api/admin/problem-spaces',async(req,res)=>{if(!legacyAdminOk(req))return res.status(401).json({error:'Use the signed-in admin dashboard for approvals.'});try{return res.json({requests:await service.listAdmin()})}catch(error){console.error(error);return res.status(500).json({error:'Admin queue is temporarily unavailable.'})}});
 router.patch('/api/admin/problem-spaces/:id',async(req,res)=>{if(!legacyAdminOk(req))return res.status(401).json({error:'Use the signed-in admin dashboard for approvals.'});try{const row=await service.update(req.params.id,String(req.body?.status||''));return row?res.json({request:row}):res.status(404).json({error:'Request not found.'})}catch(error){return res.status(400).json({error:error.message})}});return router;
}
