import express from 'express';
import crypto from 'node:crypto';

const DEFAULT_MODEL='sonar-pro',MAX_REPORTS=160;
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m),num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clamp=v=>Math.min(100,Math.max(0,num(v)));
const list=(v,m=30,n=700)=>(Array.isArray(v)?v:[]).map(x=>clean(x,n)).filter(Boolean).slice(0,m);
const split=(v,m=20,n=180)=>(Array.isArray(v)?v:String(v||'').split(/\n|,/)).map(x=>clean(x,n)).filter(Boolean).slice(0,m);
const rows=(v,fn,m=30)=>(Array.isArray(v)?v:[]).map(fn).filter(Boolean).slice(0,m);
const route=fn=>async(req,res)=>{try{await fn(req,res)}catch(error){console.error('Proposition request:',error);res.status(error.status||500).json({error:error.message||'Proposition request failed.'})}};
const slugify=v=>clean(v,160).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'proposition';

export function parsePropositionJson(raw){if(raw&&typeof raw==='object')return raw;const text=String(raw||'').trim(),candidate=text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]||text,first=candidate.indexOf('{'),last=candidate.lastIndexOf('}');if(first<0||last<=first)throw Object.assign(new Error('The research provider did not return a JSON proposition.'),{status:502});try{return JSON.parse(candidate.slice(first,last+1))}catch(error){throw Object.assign(new Error(`The research provider returned malformed JSON: ${error.message}`),{status:502})}}
function source(x){const url=clean(x?.url,900),title=clean(x?.title||x?.name||url,240);return!url&&!title?null:{title:title||url,url:/^https?:\/\//i.test(url)?url:'',publisher:clean(x?.publisher,160),date:clean(x?.date,60),claim:clean(x?.claim||x?.supports||x?.summary,1200)}}
function economics(v={}){const price=Math.max(0,num(v.price)),landed=Math.max(0,num(v.landed_cost??v.landedCost)),fulfillment=Math.max(0,num(v.fulfillment)),fees=Math.max(0,num(v.fees)),marketing=Math.max(0,num(v.marketing)),contribution=num(v.contribution,price-landed-fulfillment-fees-marketing);return{currency:clean(v.currency,10)||'USD',price,landed_cost:landed,fulfillment,fees,marketing,contribution:Number(contribution.toFixed(2)),margin_percent:Number(num(v.margin_percent??v.marginPercent,price?contribution/price*100:0).toFixed(1)),break_even_units:Math.max(0,Math.round(num(v.break_even_units??v.breakEvenUnits))),notes:list(v.notes,20,500)}}
function budget(v={}){const items=rows(v.items,x=>clean(x?.label,120)?{label:clean(x.label,120),amount:Math.max(0,num(x.amount)),category:clean(x.category,80)||'Other'}:null,30);return{currency:clean(v.currency,10)||'USD',low:Math.max(0,num(v.low)),base:Math.max(0,num(v.base,items.reduce((s,x)=>s+x.amount,0))),high:Math.max(0,num(v.high)),items,notes:list(v.notes,20,500)}}

export function normalizePropositionReport(input={}, {brief={},current=null,currentUser=null,model=null,citations=[]}={}){
 const d=input.report&&typeof input.report==='object'?input.report:input,now=new Date().toISOString(),project=clean(d.project_name||d.projectName||brief.projectName||current?.project_name||'Untitled proposition',180),id=clean(current?.id||d.id,120)||crypto.randomUUID(),unit=economics(d.unit_economics||d.unitEconomics),cost=budget(d.budget||d.costs);
 if(!unit.break_even_units&&unit.contribution>0&&cost.base>0)unit.break_even_units=Math.ceil(cost.base/unit.contribution);
 const sources=new Map();for(const x of [...(d.sources||[]),...citations.map(url=>({title:url,url}))].map(source).filter(Boolean))sources.set(x.url||`${x.publisher}:${x.title}`,x);
 const implementation=rows(d.implementation_plan||d.implementationPlan||d.launch_plan||d.launchPlan,x=>clean(x?.phase||x?.name,160)?{phase:clean(x.phase||x.name,160),timing:clean(x.timing,120),owner:clean(x.owner,160),objective:clean(x.objective,800),actions:list(x.actions,18,500),gate:clean(x.gate||x.decision_gate,800)}:null,16);
 return{id,slug:clean(current?.slug||d.slug,120)||`${slugify(project)}-${id.slice(0,8)}`,user_id:current?.user_id||currentUser?.id||clean(d.user_id,120)||'atlas-harbor-demo',author_alias:clean(d.author_alias||currentUser?.user_metadata?.atlas_profile?.username||current?.author_alias||'Atlas Harbor research',80),title:clean(d.title||`${project} proposition`,240),project_name:project,proposition_type:clean(d.proposition_type||d.propositionType||brief.propositionType||current?.proposition_type||'General proposition',120),organizations:split(d.organizations||brief.organizations||current?.organizations),website:clean(d.website||brief.website||current?.website,800),proposition:clean(d.proposition||brief.proposition||current?.proposition,5000),current_state:clean(d.current_state||d.currentState||brief.currentState||current?.current_state,4000),problem_statement:clean(d.problem_statement||d.problemStatement||brief.problemStatement||current?.problem_statement,4000),decision_audience:clean(d.decision_audience||d.decisionAudience||brief.decisionAudience||current?.decision_audience,1200),decision_requested:clean(d.decision_requested||d.decisionRequested||brief.decisionRequested||brief.pitchObjective||current?.decision_requested||current?.pitch_objective,1800),why_now:clean(d.why_now||d.whyNow||brief.whyNow||current?.why_now,1800),scope:clean(d.scope||brief.scope||current?.scope,1200),geography:clean(d.geography||brief.geography||current?.geography||'Not geography-dependent',180),timeline:clean(d.timeline||brief.timeline||current?.timeline,300),financial_frame:clean(d.financial_frame||d.financialFrame||brief.financialFrame||brief.targetPrice||current?.financial_frame,1200),route_to_market:clean(d.route_to_market||d.routeToMarket||brief.adoptionPath||brief.routeToMarket||current?.route_to_market,500),partner_profile:clean(d.partner_profile||d.partnerProfile||brief.partnerProfile||current?.partner_profile,1800),pitch_objective:clean(d.pitch_objective||d.pitchObjective||brief.pitchObjective||brief.decisionRequested||current?.pitch_objective,1800),constraints:clean(d.constraints||brief.constraints||current?.constraints,3000),evidence_available:clean(d.evidence_available||d.evidenceAvailable||brief.evidenceAvailable||current?.evidence_available,3000),research_query:clean(d.research_query||d.query||brief.query||current?.research_query,7000),status:'published',generated_at:current?.generated_at||now,updated_at:now,model:clean(model||d.model||current?.model||'starter-brief',160),executive_summary:clean(d.executive_summary||d.executiveSummary,7000),recommendation:clean(d.recommendation||d.verdict,3500),call_to_action:clean(d.call_to_action||d.callToAction||d.decision_requested||brief.decisionRequested,1800),confidence:['high','medium','low','preliminary'].includes(d.confidence)?d.confidence:'preliminary',
 metrics:rows(d.metrics,x=>clean(x?.label||x?.name,140)?{label:clean(x.label||x.name,140),value:clean(x.value,100),unit:clean(x.unit,60),detail:clean(x.detail||x.note,600),kind:clean(x.kind,40)||'text',confidence:['high','medium','low','assumption'].includes(x.confidence)?x.confidence:'low'}:null,24),
 evidence_summary:rows(d.evidence_summary||d.evidenceSummary,x=>clean(x?.claim,240)?{claim:clean(x.claim,240),evidence:clean(x.evidence,1400),confidence:['high','medium','low','assumption'].includes(x.confidence)?x.confidence:'low',source_urls:split(x.source_urls||x.sourceUrls,8,900).filter(url=>/^https?:\/\//i.test(url)),verification:clean(x.verification||x.next_step,800)}:null,30),
 stakeholders:rows(d.stakeholders,x=>clean(x?.name||x?.group,180)?{name:clean(x.name||x.group,180),role:clean(x.role,300),interest:clean(x.interest,800),influence:clamp(x.influence),concern:clean(x.concern||x.objection,800)}:null,24),
 outcomes:rows(d.outcomes,x=>clean(x?.outcome||x?.name,220)?{outcome:clean(x.outcome||x.name,220),baseline:clean(x.baseline,180),target:clean(x.target,180),timeframe:clean(x.timeframe,120),measurement:clean(x.measurement,700)}:null,20),
 alternatives:rows(d.alternatives,x=>clean(x?.name,180)?{name:clean(x.name,180),description:clean(x.description,900),benefits:list(x.benefits,12,500),costs:list(x.costs,12,500),risks:list(x.risks,12,500),score:clamp(x.score)}:null,16),
 strategic_fit:{alignment:clean(d.strategic_fit?.alignment||d.strategicFit?.alignment,1600),capabilities:list(d.strategic_fit?.capabilities||d.strategicFit?.capabilities,20,500),dependencies:list(d.strategic_fit?.dependencies||d.strategicFit?.dependencies,20,500)},
 success_metrics:rows(d.success_metrics||d.successMetrics,x=>clean(x?.metric||x?.name,180)?{metric:clean(x.metric||x.name,180),baseline:clean(x.baseline,160),target:clean(x.target,160),timeframe:clean(x.timeframe,120),owner:clean(x.owner,160)}:null,24),
 objections:rows(d.objections,x=>clean(x?.objection||x?.concern,240)?{objection:clean(x.objection||x.concern,240),response:clean(x.response,1200),evidence_needed:clean(x.evidence_needed||x.evidenceNeeded,900)}:null,20),
 audience_segments:rows(d.audience_segments||d.audienceSegments,x=>clean(x?.name,160)?{name:clean(x.name,160),share:clamp(x.share),description:clean(x.description,900),need:clean(x.need,500),channel:clean(x.channel,300)}:null,14),
 demand_signals:rows(d.demand_signals||d.demandSignals,x=>clean(x?.signal||x?.name,180)?{signal:clean(x.signal||x.name,180),score:clamp(x.score),evidence:clean(x.evidence,1100),verification:clean(x.verification,700),confidence:['high','medium','low','assumption'].includes(x.confidence)?x.confidence:'low'}:null,20),
 market_sizing:{currency:clean(d.market_sizing?.currency||d.marketSizing?.currency,10)||'USD',tam:Math.max(0,num(d.market_sizing?.tam??d.marketSizing?.tam)),sam:Math.max(0,num(d.market_sizing?.sam??d.marketSizing?.sam)),som:Math.max(0,num(d.market_sizing?.som??d.marketSizing?.som)),label:clean(d.market_sizing?.label||d.marketSizing?.label,300),assumptions:list(d.market_sizing?.assumptions||d.marketSizing?.assumptions,20,700)},unit_economics:unit,budget:cost,
 competitors:rows(d.competitors,x=>clean(x?.name,160)?{name:clean(x.name,160),positioning:clean(x.positioning,700),price_range:clean(x.price_range||x.priceRange,100),advantage:clean(x.advantage,500),gap:clean(x.gap,500),url:/^https?:\/\//i.test(clean(x.url,800))?clean(x.url,800):''}:null,20),channels:rows(d.channels,x=>clean(x?.name,160)?{name:clean(x.name,160),fit:clamp(x.fit),cost:clean(x.cost,160),speed:clean(x.speed,160),notes:clean(x.notes,700)}:null,16),funnel:rows(d.funnel,x=>clean(x?.stage,120)?{stage:clean(x.stage,120),value:Math.max(0,num(x.value)),label:clean(x.label,180)}:null,12),implementation_plan:implementation,launch_plan:implementation,
 partnership:{ideal_partner:clean(d.partnership?.ideal_partner||d.partnership?.idealPartner,1400),structure:clean(d.partnership?.structure,1400),partner_value:clean(d.partnership?.partner_value||d.partnership?.partnerValue,1400),ask:clean(d.partnership?.ask,1400),terms:clean(d.partnership?.terms,1400),proof_needed:list(d.partnership?.proof_needed||d.partnership?.proofNeeded,20,600)},creative_direction:{front:clean(d.creative_direction?.front||d.creativeDirection?.front,600),back:clean(d.creative_direction?.back||d.creativeDirection?.back,600),tag:clean(d.creative_direction?.tag||d.creativeDirection?.tag,600),materials:clean(d.creative_direction?.materials||d.creativeDirection?.materials,600),packaging:clean(d.creative_direction?.packaging||d.creativeDirection?.packaging,600),campaigns:list(d.creative_direction?.campaigns||d.creativeDirection?.campaigns,20,600)},
 risks:rows(d.risks,x=>clean(x?.risk||x?.name,220)?{risk:clean(x.risk||x.name,220),likelihood:clean(x.likelihood,80),impact:clean(x.impact,80),mitigation:clean(x.mitigation,900)}:null,24),experiments:rows(d.experiments,x=>clean(x?.name,180)?{name:clean(x.name,180),hypothesis:clean(x.hypothesis,900),budget:Math.max(0,num(x.budget)),duration:clean(x.duration,120),success:clean(x.success,700),stop:clean(x.stop,700)}:null,24),sources:[...sources.values()].slice(0,80),assumptions:list(d.assumptions,50,800),research_gaps:list(d.research_gaps||d.researchGaps,50,800),changelog:list(d.changelog,24,600),needs_refresh:Boolean(d.needs_refresh)}
}

export function buildPropositionPrompt(brief={}, {feedback='',currentReport=null}={}){return`Produce a decision-grade, data-based proposition using current research where external evidence is relevant. The proposition may be an internal work project; a partnership between companies; a sales pitch; an investment, program, policy, vendor, or operating decision; or a product, brand, or market entry. Do not force a market-launch framework onto an internal project or operational decision. Identify the decision-maker, requested action, current problem, evidence, alternatives, implementation requirements, financial implications, risks, objections, and measurable outcomes.\n\nEvidence rules:\n- Cite every quantitative or externally verifiable claim with a direct URL.\n- Treat facts supplied in the brief as user-provided context, not independently verified evidence.\n- Separate sourced facts, calculations, assumptions, and recommendations.\n- Never invent internal company data, market sizes, prices, customer results, competitor facts, or citations.\n- When data is unavailable, state the gap and propose a practical verification method.\n- Leave market-specific sections empty when they are not relevant.\n\nPROPOSITION BRIEF\n${JSON.stringify({...brief,modules:list(brief.modules,30,120)},null,2)}${currentReport?`\nCURRENT PROPOSITION\n${JSON.stringify(currentReport)}`:''}${feedback?`\nUSER FEEDBACK\n${clean(feedback,7000)}`:''}\n\nReturn only valid JSON with these keys: title, project_name, proposition_type, organizations, website, proposition, current_state, problem_statement, decision_audience, decision_requested, why_now, scope, geography, timeline, financial_frame, route_to_market, partner_profile, pitch_objective, constraints, evidence_available, research_query, executive_summary, recommendation, call_to_action, confidence, metrics, evidence_summary, stakeholders, outcomes, alternatives, strategic_fit, success_metrics, objections, audience_segments, demand_signals, market_sizing, unit_economics, budget, competitors, channels, funnel, implementation_plan, partnership, creative_direction, risks, experiments, sources, assumptions, research_gaps. Numeric values must be numbers. Include at least 6 useful metrics, 5 evidence claims, 3 stakeholders, realistic alternatives, 3 implementation phases, 5 risks or objections, 3 validation steps, and 8 sources when external evidence is available.`}
async function perplexity(fetchImpl,{apiKey,model,prompt}){if(!apiKey)throw Object.assign(new Error('Perplexity API key required.'),{status:400});const response=await fetchImpl('https://api.perplexity.ai/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:clean(model,120)||DEFAULT_MODEL,messages:[{role:'system',content:'Return rigorous, source-aware proposition research as one valid JSON object only.'},{role:'user',content:prompt}],temperature:.15}),signal:AbortSignal.timeout(120000)}),raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{}if(!response.ok)throw Object.assign(new Error(data?.error?.message||data?.message||raw||`Perplexity returned ${response.status}.`),{status:response.status});return{report:parsePropositionJson(data.choices?.[0]?.message?.content),model:data.model||model||DEFAULT_MODEL,citations:Array.isArray(data.citations)?data.citations:[]}}

const example=(id,title,type,proposition,decision)=>normalizePropositionReport({id,slug:id,title,project_name:title.replace(/ —.*/,''),proposition_type:type,proposition,decision_requested:decision,executive_summary:'Illustrative starter proposition. Replace assumptions with live external research and relevant internal data.',recommendation:'Run a bounded evidence and validation phase before making a larger commitment.',call_to_action:decision,confidence:'preliminary',needs_refresh:true,metrics:[{label:'Evidence readiness',value:'25',unit:'/100',detail:'Illustrative until refreshed.',confidence:'low'},{label:'Decision stage',value:'Pilot',unit:'',detail:'Use a bounded next step.',confidence:'assumption'}],alternatives:[{name:'Proposed pilot',description:'Test the proposition with explicit gates.',benefits:['Fast learning'],costs:['Time and budget'],risks:['Weak evidence'],score:80},{name:'Improve current approach',description:'Change the existing process without the full proposition.',benefits:['Lower disruption'],costs:['Less learning'],risks:['Problem may persist'],score:55},{name:'Do nothing',description:'Maintain the status quo.',benefits:['No immediate cost'],costs:['Opportunity cost'],risks:['Existing problem continues'],score:25}],implementation_plan:[{phase:'Evidence',timing:'Phase 1',objective:'Establish baseline and feasibility.',actions:['Collect sources','Validate internal context'],gate:'Proceed only if evidence supports a test.'},{phase:'Pilot',timing:'Phase 2',objective:'Run a bounded test.',actions:['Implement','Measure','Review'],gate:'Stop, revise, or expand using agreed metrics.'},{phase:'Decision',timing:'Phase 3',objective:'Choose the next commitment.',actions:['Compare outcomes','Resolve objections'],gate:'Scale only with credible evidence.'}],risks:[{risk:'Evidence is incomplete',likelihood:'High',impact:'High',mitigation:'Use explicit verification tasks.'}],experiments:[{name:'Bounded pilot',hypothesis:'The proposition improves the agreed outcome.',budget:0,duration:'To be set',success:'Success metrics improve.',stop:'Stop if evidence or implementation fails.'}],assumptions:['All values are illustrative.'],research_gaps:['External evidence','Internal baseline','Stakeholder interviews']});
const EXAMPLES=[example('the-way-starter-brief','The Way — apparel partnership','Company partnership and product launch','Create a premium minimalist apparel capsule around “The Way” with discreet The Way Version attribution and partner-operated fulfillment.','Approve a gated partner pilot.'),example('work-intake-pilot-example','Shared Work Intake — internal pilot','Internal work project','Replace fragmented request channels with one structured intake, triage, ownership, and prioritization pilot.','Approve a 60-day pilot and capped budget.'),example('company-partnership-example','Joint Market Intelligence — company partnership','Partnership between companies','Combine an analytics product with a trusted industry network in a bounded data and distribution pilot.','Authorize joint diligence and a six-month pilot.'),example('enterprise-sales-example','Uptime Analytics — sales case','B2B sales pitch','Run a paid one-site analytics pilot to identify recurring downtime patterns and prioritize interventions.','Approve technical discovery and a 12-week paid pilot.')];
const DEFAULT={version:2,reports:EXAMPLES,updatedAt:EXAMPLES[0].updated_at};

export function createPropositionRouter({storage,fetchImpl=globalThis.fetch}={}){if(!storage)throw new Error('Proposition storage is required.');const router=express.Router(),hits=new Map();
 const state=async current=>{const stored=await storage.readGlobal('go_to_market',{fallbackCurrent:current,defaults:DEFAULT}),merged=new Map(EXAMPLES.map(x=>[x.id,x]));for(const x of stored.reports||[])merged.set(x.id,x);return{...DEFAULT,...stored,reports:[...merged.values()]}};
 const find=async(id,current)=>(await state(current)).reports?.find(x=>x.id===id||x.slug===id)||null;
 const save=(report,current)=>storage.writeGlobal('go_to_market',value=>({...DEFAULT,...value,reports:[report,...((value.reports||[]).filter(x=>x.id!==report.id)),...EXAMPLES.filter(x=>x.id!==report.id&&!(value.reports||[]).some(y=>y.id===x.id))].slice(0,MAX_REPORTS),updatedAt:new Date().toISOString()}),{fallbackCurrent:current});
 const limit=key=>{const now=Date.now();if(now-(hits.get(key)||0)<30000)throw Object.assign(new Error('Wait 30 seconds before starting another proposition-research request.'),{status:429});hits.set(key,now)};
 router.get('/api/prop/status',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false}),data=await state(current);res.set('Cache-Control','no-store');res.json({ok:true,signedIn:Boolean(current),storage:storage.configured?'supabase-account-metadata':'unavailable',reportCount:data.reports?.length||0,credentialStorage:'browser-local',requiresValidatedPerplexityKey:true,canonicalPath:'/prop'})}));
 router.post('/api/prop/perplexity/test',route(async(req,res)=>{await storage.requestUser(req);const apiKey=clean(req.get('x-perplexity-key'),500);if(!apiKey)throw Object.assign(new Error('Perplexity API key required.'),{status:400});const selected=clean(req.body?.model,120)||DEFAULT_MODEL,response=await fetchImpl('https://api.perplexity.ai/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:selected,messages:[{role:'user',content:'Reply with only: proposition research ready'}],temperature:0}),signal:AbortSignal.timeout(30000)}),raw=await response.text();let data={};try{data=JSON.parse(raw)}catch{}if(!response.ok)throw Object.assign(new Error(data?.error?.message||data?.message||raw||`Perplexity returned ${response.status}.`),{status:response.status});res.json({ok:true,model:data.model||selected,response:data.choices?.[0]?.message?.content||''})}));
 router.get('/api/prop/reports',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false}),q=clean(req.query.q,240).toLowerCase();let reports=(await state(current)).reports?.filter(x=>x.status==='published')||[];if(q)reports=reports.filter(x=>[x.title,x.project_name,x.proposition_type,x.proposition,x.decision_audience,x.decision_requested,x.geography,x.route_to_market,x.partner_profile,...(x.organizations||[])].join(' ').toLowerCase().includes(q));reports=reports.sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at))).slice(0,160).map(x=>({id:x.id,slug:x.slug,title:x.title,project_name:x.project_name,proposition_type:x.proposition_type||'Proposition',organizations:x.organizations||[],proposition:x.proposition,decision_requested:x.decision_requested||x.pitch_objective,geography:x.geography,route_to_market:x.route_to_market,recommendation:x.recommendation,confidence:x.confidence,updated_at:x.updated_at,model:x.model,needs_refresh:x.needs_refresh,is_owner:current?.id===x.user_id}));res.json({reports,total:reports.length,storage:'supabase-account-metadata'})}));
 router.get('/api/prop/reports/:id',route(async(req,res)=>{const{current}=await storage.requestUser(req,{required:false}),report=await find(req.params.id,current);if(!report||report.status!=='published')throw Object.assign(new Error('Proposition not found.'),{status:404});res.set('Cache-Control','public,max-age=30,stale-while-revalidate=300');res.json({report:{...report,is_owner:current?.id===report.user_id}})}));
 router.post('/api/prop/reports',route(async(req,res)=>{const{current}=await storage.requestUser(req);limit(`create:${current.id}`);const brief=req.body?.brief||{};if(clean(brief.projectName,180).length<2)throw Object.assign(new Error('Enter a project or proposition name.'),{status:400});if(clean(brief.proposition,5000).length<20)throw Object.assign(new Error('Describe the proposition in at least 20 characters.'),{status:400});if(clean(brief.decisionRequested||brief.pitchObjective,1800).length<8)throw Object.assign(new Error('Describe the decision or action you want.'),{status:400});const result=await perplexity(fetchImpl,{apiKey:clean(req.get('x-perplexity-key'),500),model:req.body?.model,prompt:buildPropositionPrompt(brief)}),report=normalizePropositionReport(result.report,{brief,currentUser:current,model:result.model,citations:result.citations});await save(report,current);res.status(201).json({report})}));
 router.post('/api/prop/reports/:id/regenerate',route(async(req,res)=>{const{current}=await storage.requestUser(req);limit(`regenerate:${current.id}:${req.params.id}`);const existing=await find(req.params.id,current);if(!existing)throw Object.assign(new Error('Proposition not found.'),{status:404});const isExample=EXAMPLES.some(x=>x.id===existing.id);if(existing.user_id!==current.id&&!isExample)throw Object.assign(new Error('Only the creator can regenerate this proposition.'),{status:403});const brief={projectName:existing.project_name,propositionType:existing.proposition_type,organizations:existing.organizations,website:existing.website,proposition:existing.proposition,currentState:existing.current_state,problemStatement:existing.problem_statement,decisionAudience:existing.decision_audience,decisionRequested:existing.decision_requested||existing.pitch_objective,whyNow:existing.why_now,scope:existing.scope,geography:existing.geography,timeline:existing.timeline,financialFrame:existing.financial_frame,adoptionPath:existing.route_to_market,partnerProfile:existing.partner_profile,constraints:existing.constraints,evidenceAvailable:existing.evidence_available,query:existing.research_query,modules:req.body?.modules||[]},result=await perplexity(fetchImpl,{apiKey:clean(req.get('x-perplexity-key'),500),model:req.body?.model,prompt:buildPropositionPrompt(brief,{feedback:req.body?.feedback,currentReport:existing})}),base=isExample?{...existing,id:crypto.randomUUID(),slug:''}:existing,report=normalizePropositionReport(result.report,{brief,current:base,currentUser:current,model:result.model,citations:result.citations});report.user_id=current.id;report.author_alias=current.user_metadata?.atlas_profile?.username||report.author_alias;report.needs_refresh=false;report.changelog=[clean(req.body?.feedback,600),...(existing.changelog||[])].filter(Boolean).slice(0,24);await save(report,current);res.json({report})}));
 router.patch('/api/prop/reports/:id',route(async(req,res)=>{const{current}=await storage.requestUser(req),existing=await find(req.params.id,current);if(!existing)throw Object.assign(new Error('Proposition not found.'),{status:404});if(existing.user_id!==current.id)throw Object.assign(new Error('Only the creator can update this proposition.'),{status:403});const report=normalizePropositionReport(req.body?.report||req.body||{},{current:existing,currentUser:current,model:clean(req.body?.model,160)||existing.model});report.changelog=[clean(req.body?.changeSummary,600),...(existing.changelog||[])].filter(Boolean).slice(0,24);await save(report,current);res.json({report})}));return router}
