import express from 'express';

const safeSummary=row=>({id:row.id||null,share_token:row.share_token||null,title:String(row.title||'Untitled analysis'),resource_title:String(row.resource_title||'Analysis'),resource_type:String(row.resource_type||'analysis'),resource_id:String(row.resource_id||''),published_at:row.published_at||row.updated_at||row.created_at||null,updated_at:row.updated_at||row.published_at||row.created_at||null,author_username:String(row.author_username||'Atlas Author'),author_avatar_seed:String(row.author_avatar_seed||''),author_profile_slug:String(row.author_profile_slug||''),featured:row.featured!==false});
const safeDetail=(row,isOwner=false)=>({...safeSummary(row),body:String(row.body||''),projections:Array.isArray(row.projections)?row.projections:[],comments_enabled:Boolean(row.comments_enabled),share_ai_analysis:row.share_ai_analysis!==false,is_owner:Boolean(isOwner)});
const published=row=>Boolean(row&&row.is_shared&&row.is_published&&row.share_token);
const discoverable=row=>published(row)&&row.featured!==false;
async function readJson(response){const text=await response.text();if(!response.ok)throw new Error(text||`Request failed (${response.status})`);try{return text?JSON.parse(text):null}catch{return null}}

export function createPublishedFeedRouter({env=process.env,fetchImpl=globalThis.fetch}={}){
 const router=express.Router(),base=env.SUPABASE_URL,publishable=env.SUPABASE_PUBLISHABLE_KEY,secret=env.SUPABASE_SECRET_KEY;
 async function accounts(req){const found=[];if(!base||!publishable)return found;const bearer=String(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(bearer)try{const response=await fetchImpl(`${base}/auth/v1/user`,{headers:{apikey:publishable,Authorization:`Bearer ${bearer}`}});if(response.ok)found.push(await readJson(response))}catch(error){console.warn('Current account lookup unavailable:',error.message)}if(secret)try{const response=await fetchImpl(`${base}/auth/v1/admin/users?per_page=1000`,{headers:{apikey:secret,Authorization:`Bearer ${secret}`}}),data=await readJson(response);for(const account of data?.users||[])if(!found.some(item=>item.id===account.id))found.push(account)}catch(error){console.warn('Global account lookup unavailable:',error.message)}return found}
 async function collect(req,{token=null,profileSlug=null,includeUnfeatured=false}={}){
  if(!base||!publishable)return[];
  const allAccounts=await accounts(req),profileByUser=new Map(allAccounts.map(account=>[account.id,account?.user_metadata?.atlas_profile||{}])),rows=[];
  try{const query=token?`?share_token=eq.${encodeURIComponent(token)}&is_shared=eq.true&is_published=eq.true&select=*&limit=1`:'?is_shared=eq.true&is_published=eq.true&select=*&order=published_at.desc.nullslast,updated_at.desc&limit=250';const response=await fetchImpl(`${base}/rest/v1/workspace_notes${query}`,{headers:{apikey:publishable}});if(response.ok)for(const original of await readJson(response)||[]){const profile=profileByUser.get(original.user_id)||{},row={...original,author_username:profile.username||original.author_username,author_avatar_seed:profile.avatar_seed||original.author_avatar_seed,author_profile_slug:profile.profile_slug||original.author_profile_slug};if((includeUnfeatured?published(row):discoverable(row))&&(!profileSlug||row.author_profile_slug===profileSlug))rows.push(row)}}catch(error){console.warn('Published table feed unavailable:',error.message)}
  for(const account of allAccounts){const profile=account?.user_metadata?.atlas_profile||{},records=account?.user_metadata?.atlas_virtual_tables?.workspace_notes;if(!Array.isArray(records))continue;if(profileSlug&&profile.profile_slug!==profileSlug)continue;for(const original of records){const row={...original,author_username:profile.username||original.author_username,author_avatar_seed:profile.avatar_seed||original.author_avatar_seed,author_profile_slug:profile.profile_slug||original.author_profile_slug};if((includeUnfeatured?published(row):discoverable(row))&&(!token||row.share_token===token))rows.push(row)}}return{rows,accounts:allAccounts}
 }
 router.get('/api/published-feed',async(req,res)=>{const{rows:combined}=await collect(req),unique=new Map();for(const row of combined){const key=row.share_token||row.id;if(key)unique.set(key,safeSummary(row))}const publications=[...unique.values()].sort((a,b)=>new Date(b.published_at||b.updated_at||0)-new Date(a.published_at||a.updated_at||0)).slice(0,250);res.set('Cache-Control','public,max-age=15,stale-while-revalidate=60');res.json({publications})});
 router.get('/api/published-feed/:token',async(req,res)=>{const{rows,accounts:allAccounts}=await collect(req,{token:req.params.token,includeUnfeatured:true}),row=rows.find(item=>item.share_token===req.params.token),bearer=String(req.get('authorization')||'').replace(/^Bearer\s+/i,''),current=bearer?allAccounts[0]:null,isOwner=Boolean(row&&current&&row.user_id===current.id);res.set('Cache-Control','no-store');return row?res.json({publication:safeDetail(row,isOwner)}):res.status(404).json({error:'This publication was not found or is no longer shared.'})});
 router.patch('/api/published-feed/:token/featured',async(req,res)=>{if(!base||!publishable)return res.status(503).json({error:'Account storage is unavailable.'});const bearer=String(req.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!bearer)return res.status(401).json({error:'Sign in required.'});const accountResponse=await fetchImpl(`${base}/auth/v1/user`,{headers:{apikey:publishable,Authorization:`Bearer ${bearer}`}});if(!accountResponse.ok)return res.status(401).json({error:'Your session expired. Sign in again.'});const account=await readJson(accountResponse),featured=req.body?.featured!==false,records=account?.user_metadata?.atlas_virtual_tables?.workspace_notes||[],index=records.findIndex(row=>row.share_token===req.params.token&&row.user_id===account.id);
  if(index>=0){const next=[...records];next[index]={...next[index],featured,updated_at:new Date().toISOString()};const metadata={...(account.user_metadata||{}),atlas_virtual_tables:{...(account.user_metadata?.atlas_virtual_tables||{}),workspace_notes:next}};const response=await fetchImpl(`${base}/auth/v1/user`,{method:'PUT',headers:{apikey:publishable,Authorization:`Bearer ${bearer}`,'Content-Type':'application/json'},body:JSON.stringify({data:metadata})});if(!response.ok)return res.status(response.status).json({error:'Could not save publication visibility.'});return res.json({ok:true,featured})}
  try{const response=await fetchImpl(`${base}/rest/v1/workspace_notes?share_token=eq.${encodeURIComponent(req.params.token)}&user_id=eq.${encodeURIComponent(account.id)}`,{method:'PATCH',headers:{apikey:publishable,Authorization:`Bearer ${bearer}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({featured,updated_at:new Date().toISOString()})});if(response.ok)return res.json({ok:true,featured})}catch{}
  return res.status(404).json({error:'Publication not found in your account.'})
 });
 router.get('/api/profiles/:slug',async(req,res)=>{const slug=String(req.params.slug||''),allAccounts=await accounts(req),account=allAccounts.find(item=>item?.user_metadata?.atlas_profile?.profile_slug===slug),profile=account?.user_metadata?.atlas_profile;if(!profile)return res.status(404).json({error:'Profile not found.'});const{rows}=await collect(req,{profileSlug:slug}),publications=rows.map(safeSummary).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0));res.set('Cache-Control','public,max-age=30,stale-while-revalidate=120');res.json({profile:{username:profile.username,avatar_seed:profile.avatar_seed,profile_slug:profile.profile_slug},publications})});
 return router;
}
